import { execSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import type { IPrimitiveManifestEntry, IWebUiManifest } from '../types';

/**
 * Bundle-size assertions per subpath in @capsuletech/web-ui.
 *
 * Source of truth: `dist/manifest.json` generated by `pnpm build:manifest`.
 *
 * Two classes of assertions:
 *   (a) Size caps — L0 primitives must stay under a small budget
 *       (peer deps are external — these numbers reflect ONLY our code).
 *   (b) Graph hygiene — L0 subpaths must NOT pull any Kobalte interactive
 *       primitive into their externals (allowlist: polymorphic / separator
 *       / skeleton — these are featherweight role-bearers, not behavioral).
 *
 * Canon: docs/_meta/web-ui.md section "Weight gradient & size manifest".
 *
 * Calibrated 2026-06-12 after fixing build-manifest external resolution
 * (regex → glob patterns) + barrel split (input/index.ts no longer
 * re-exports Select/Textarea) + Spinner-instead-of-lucide swap in Button.
 */

// ---------------------------------------------------------------------------
// Calibrated limits (kB gzip) — L0 only.
// L1 has no size cap (consumer brings the Kobalte peer dep).
// ---------------------------------------------------------------------------
const L0_SIZE_LIMIT_KB = 12;

// ---------------------------------------------------------------------------
// Kobalte allowlist — featherweight role-bearing subpaths permitted in L0 graph.
// Everything else from @kobalte/core/* is "interactive" → forbidden in L0.
// ---------------------------------------------------------------------------
const KOBALTE_ALLOWLIST = ['@kobalte/core/polymorphic', '@kobalte/core/separator', '@kobalte/core/skeleton'];

// ---------------------------------------------------------------------------
// Load manifest at module-eval time — `it.each` needs the data NOW to declare tests.
// If missing, fall back to build:manifest synchronously (covers fresh checkouts).
// ---------------------------------------------------------------------------
const packageRoot = resolve(__dirname, '../../..');
const manifestPath = resolve(packageRoot, 'dist/manifest.json');

if (!existsSync(manifestPath)) {
  execSync('pnpm build', { cwd: packageRoot, stdio: 'inherit' });
  execSync('pnpm build:manifest', { cwd: packageRoot, stdio: 'inherit' });
}

const manifest: IWebUiManifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const L0_ENTRIES = manifest.primitives.filter((p) => p.weight === 'L0');
const L1_ENTRIES = manifest.primitives.filter((p) => p.weight === 'L1');

describe('@capsuletech/web-ui — bundle size assertions', () => {
  it('manifest is non-empty and has expected shape', () => {
    expect(manifest.version).toBeTruthy();
    expect(manifest.generatedAt).toBeTruthy();
    expect(Array.isArray(manifest.primitives)).toBe(true);
    expect(manifest.primitives.length).toBeGreaterThan(15);
  });

  describe('L0 size caps — must stay under budget', () => {
    it.each<[string, number]>(L0_ENTRIES.map((p) => [p.name, p.sizeKB]))(
      'L0 subpath "%s" is %s kB (budget: %s kB)',
      (_name, sizeKB) => {
        expect(sizeKB).toBeLessThanOrEqual(L0_SIZE_LIMIT_KB);
      },
    );
  });

  describe('L0 graph hygiene — must NOT contain Kobalte interactive', () => {
    it.each<[string, string[]]>(
      L0_ENTRIES.map((p) => [p.name, p.externals.filter((e) => e.startsWith('@kobalte/'))]),
    )('L0 subpath "%s" Kobalte deps are allowlisted', (_name, kobalteDeps) => {
      const forbidden = kobalteDeps.filter((dep) => !KOBALTE_ALLOWLIST.includes(dep));
      expect(forbidden).toEqual([]);
    });
  });

  describe('L1 sanity — non-empty externals', () => {
    it.each<[string, string[]]>(L1_ENTRIES.map((p) => [p.name, p.externals]))(
      'L1 subpath "%s" has non-empty externals (consumer pays peer dep cost)',
      (_name, externals) => {
        // L1 primitives are typically thin wrappers over Kobalte/TanStack/etc.
        // They MUST have externals — if a primitive in L1 has zero externals,
        // either it's misclassified or something went wrong with measurement.
        expect(externals.length).toBeGreaterThan(0);
      },
    );
  });
});
