// generated by AppConfigPlugin — не редактировать руками
import { registerAliases } from '@capsule/web-state';
import { createApi, setApiClient } from '@capsule/web-query';
import appConfig from '../capsule.app';
import { endpoints } from './registry/endpoints';

registerAliases({
  "@login-form": [
    "email",
    "submit"
  ],
  "@header": [
    "nav",
    "logout"
  ]
});

if (appConfig.api) {
  setApiClient(createApi(appConfig.api, endpoints));
}
