import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { createJiti } from 'jiti';
import type { Plugin, ViteDevServer } from 'vite';

const loadConfigFresh = (configPath: string): unknown => {
  // moduleCache: false — каждый вызов перечитывает файл, иначе ловим закэшированный объект
  // и не видим изменений в capsule.app.ts.
  const j = createJiti(import.meta.url, { interopDefault: true, moduleCache: false });
  const mod = j(configPath) as { default?: unknown } | unknown;
  return (mod as { default?: unknown })?.default ?? mod;
};

interface AppConfigShape {
  meta?: {
    tags?: readonly string[];
  };
  aliases?: Record<string, readonly string[]>;
}

interface IProps {
  /** Абсолютный путь к `capsule.app.ts` приложения. */
  configPath: string;
  /** Куда писать .d.ts с CapsuleTags/CapsuleAliases augmentation'ом. */
  typesOut: string;
  /** Куда писать рантайм-файл с побочным эффектом `registerAliases`. */
  runtimeOut: string;
  /** Опциональный коллбэк — кому-то ещё (CompliancePlugin) нужен снимок конфига. */
  onLoad?: (config: AppConfigShape) => void;
}

const writeFile = (path: string, content: string) => {
  const dir = dirname(path);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(path, content, 'utf-8');
};

const renderInterface = (name: string, keys: readonly string[]): string => {
  if (keys.length === 0) return `  interface ${name} {}\n`;
  const entries = keys.map((k) => `    ${JSON.stringify(k)}: true;`).join('\n');
  return `  interface ${name} {\n${entries}\n  }\n`;
};

const generateTypesFile = (tags: readonly string[], aliasKeys: readonly string[]): string => {
  if (tags.length === 0 && aliasKeys.length === 0) {
    return '// generated by AppConfigPlugin — пустой capsule.app.ts\nexport {};\n';
  }
  return [
    '// generated by AppConfigPlugin — не редактировать руками',
    'declare global {',
    renderInterface('CapsuleTags', tags),
    renderInterface('CapsuleAliases', aliasKeys),
    '}',
    'export {};',
    '',
  ].join('\n');
};

/**
 * Рантайм-файл импортируется side-effect'ом из `.capsule/bootstrap.tsx`.
 * Делает три вещи в порядке выполнения:
 *  1. `registerAliases({...})` — статический JSON из `capsule.app.ts > aliases`.
 *  2. `import appConfig from '../capsule.app'` — реактивный импорт (function-поля
 *     `api({mw})` нельзя сериализовать через jiti, нужно подгрузить в браузер).
 *  3. Если `appConfig.api` задан — собирает typed-api через `createApi(...)` с
 *     auto-discovered endpoints и кладёт в `setApiClient(...)` для инжекта в Feature.
 *
 * `defineAppConfig`/`defineCapsuleConfig` в браузере — `define`-замена на identity
 * (см. `capsuleConfig.ts > define`). Поэтому импорт `../capsule.app` срабатывает
 * без рантайм-ошибки `defineAppConfig is not defined`.
 */
const generateRuntimeFile = (aliases: Record<string, readonly string[]> | undefined): string => {
  const aliasesLiteral = JSON.stringify(aliases ?? {}, null, 2);
  return [
    '// generated by AppConfigPlugin — не редактировать руками',
    "import { registerAliases } from '@capsuletech/web-state';",
    "import { createApi, setApiClient } from '@capsuletech/web-query';",
    "import appConfig from '../capsule.app';",
    "import { endpoints } from './registry/endpoints';",
    '',
    `registerAliases(${aliasesLiteral});`,
    '',
    'if (appConfig.api) {',
    '  setApiClient(createApi(appConfig.api, endpoints));',
    '}',
    '',
  ].join('\n');
};

const loadAndGenerate = (props: IProps) => {
  const { configPath, typesOut, runtimeOut, onLoad } = props;

  if (!existsSync(configPath)) {
    writeFile(typesOut, generateTypesFile([], []));
    writeFile(runtimeOut, generateRuntimeFile(undefined));
    onLoad?.({});
    return;
  }

  let config: AppConfigShape;
  try {
    config = loadConfigFresh(configPath) as AppConfigShape;
  } catch (e) {
    console.error('[appConfig] failed to load', configPath, e);
    return;
  }

  const tags = config?.meta?.tags ?? [];
  const aliases = config?.aliases ?? {};
  const aliasKeys = Object.keys(aliases);

  writeFile(typesOut, generateTypesFile(tags, aliasKeys));
  writeFile(runtimeOut, generateRuntimeFile(aliases));
  onLoad?.(config);
};

/**
 * Identifier фабрики `defineAppConfig`, которую в Node-CLI ставит
 * `@capsuletech/cli/defines.ts` на globalThis. В браузер эта фабрика не
 * попадает, поэтому при бандлинге `capsule.app.ts` нужно переписать вызовы
 * `defineAppConfig(x)` → `(x)` (identity-unwrap). Раньше это делалось через
 * esbuild `define:` со значением `'((__x__)=>__x__)'`, но новый esbuild
 * валидирует define-values жёстко (Invalid define value: must be entity
 * name or JS literal) и эта схема перестала собираться.
 *
 * `defineCapsuleConfig` здесь не нужен — он живёт в `capsule.config.ts`,
 * который Vite-config (Node-only), а не в `capsule.app.ts`. Транформ
 * срабатывает только на configPath = capsule.app.ts.
 */
const FACTORY_REPLACE_RE = /\bdefineAppConfig(?=\s*\()/g;

/**
 * Нормализация пути для сравнения id ↔ configPath:
 *  - убираем query-суффикс (Vite добавляет `?import`, `?t=<ts>` для HMR);
 *  - заменяем `\` на `/` (на Windows `path.join` отдаёт backslash, а Vite
 *    нормализует id к forward slash). Регрессионные тесты — в
 *    `__tests__/appConfig.test.ts`.
 */
const normalizePath = (p: string): string => p.split('?')[0].replace(/\\/g, '/');

export const AppConfigPlugin = (props: IProps): Plugin => {
  const targetPath = normalizePath(props.configPath);
  return {
    name: 'app-config',
    async configureServer(server: ViteDevServer) {
      loadAndGenerate(props);
      server.watcher.add(props.configPath);
      server.watcher.on('change', (file) => {
        if (normalizePath(file) === targetPath) loadAndGenerate(props);
      });
    },
    buildStart() {
      loadAndGenerate(props);
    },
    transform(code, id) {
      if (normalizePath(id) !== targetPath) return null;
      if (!FACTORY_REPLACE_RE.test(code)) return null;
      FACTORY_REPLACE_RE.lastIndex = 0;
      return {
        code: code.replace(FACTORY_REPLACE_RE, '((__x__)=>__x__)'),
        map: null,
      };
    },
  };
};
