import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import type { Plugin, ViteDevServer } from 'vite';
import { walkFiles, watcherManager } from '../utils';

const ENDPOINTS_DIR = 'endpoints';

interface Leaf {
  /** Сегменты namespace-пути в нижнем регистре (как в исходнике): `['admin','users']`. */
  segments: string[];
  /** Относительный путь файла от `endpoints/` без расширения. */
  relPath: string;
}

interface TreeNode {
  children: Map<string, TreeNode>;
  leaf?: Leaf;
}

const writeOut = (path: string, content: string) => {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf-8');
};

const fileToLeaf = (file: string, watchRoot: string): Leaf | null => {
  const rel = relative(watchRoot, file).split(/[\\/]/).filter(Boolean);
  if (rel[0] !== ENDPOINTS_DIR) return null;
  const inner = rel.slice(1);
  if (inner.length === 0) return null;
  if (inner.some((seg) => seg.startsWith('.'))) return null;
  // index.ts → родительская папка как имя сегмента (`endpoints/user/index.ts` → `user`)
  const last = inner[inner.length - 1].replace(/\.[^/.]+$/, '');
  const segments = last === 'index' ? inner.slice(0, -1) : [...inner.slice(0, -1), last];
  if (segments.length === 0) return null;
  const relPath = inner.join('/').replace(/\.[^/.]+$/, '');
  return { segments, relPath };
};

const buildTree = (leaves: Leaf[]): TreeNode => {
  const root: TreeNode = { children: new Map() };
  for (const leaf of leaves) {
    let node = root;
    for (const seg of leaf.segments) {
      let child = node.children.get(seg);
      if (!child) {
        child = { children: new Map() };
        node.children.set(seg, child);
      }
      node = child;
    }
    node.leaf = leaf;
  }
  return root;
};

/** Генерит уникальный idлокального namespace-импорта: `admin/users` → `admin__users`. */
const aliasFromSegments = (segments: string[]): string => segments.join('__');

const renderRuntimeNode = (node: TreeNode, indent: string): string => {
  if (node.leaf && node.children.size === 0) {
    return aliasFromSegments(node.leaf.segments);
  }
  // Конфликт: файл `user.ts` + папка `user/` — endpoint и namespace одновременно.
  // Не поддерживаем сейчас: либо файл, либо папка. Если будет — пользователь увидит
  // невалидный JS в registry и поправит.
  const childIndent = `${indent}  `;
  const keys = [...node.children.keys()].sort();
  const entries = keys
    .map(
      (key) => `${childIndent}${key}: ${renderRuntimeNode(node.children.get(key)!, childIndent)}`,
    )
    .join(',\n');
  return `{\n${entries}\n${indent}}`;
};

const renderRuntime = (leaves: Leaf[], srcRelFromRegistry: string): string => {
  const lines: string[] = ['// generated by EndpointsRegistryPlugin — не редактировать руками'];
  if (leaves.length === 0) {
    lines.push('export const endpoints = {} as const;');
    lines.push('export type Endpoints = typeof endpoints;');
    lines.push('');
    return lines.join('\n');
  }

  for (const leaf of leaves) {
    const alias = aliasFromSegments(leaf.segments);
    lines.push(
      `import * as ${alias} from '${srcRelFromRegistry}/${ENDPOINTS_DIR}/${leaf.relPath}';`,
    );
  }
  lines.push('');

  const tree = buildTree(leaves);
  const childIndent = '  ';
  const keys = [...tree.children.keys()].sort();
  const entries = keys
    .map(
      (key) => `${childIndent}${key}: ${renderRuntimeNode(tree.children.get(key)!, childIndent)}`,
    )
    .join(',\n');
  lines.push(`export const endpoints = {\n${entries}\n} as const;`);
  lines.push('export type Endpoints = typeof endpoints;');
  lines.push('');
  return lines.join('\n');
};

const renderTypes = (): string =>
  [
    '// generated by EndpointsRegistryPlugin — не редактировать руками',
    "import type { InferApi } from '@capsuletech/web-query';",
    "import type { Endpoints } from '../registry/endpoints';",
    '',
    'declare global {',
    '  /**',
    '   * Typed-proxy, который вернёт `createApi(...)` и инжектится в Feature',
    '   * как `services.api`. Структура — InferApi от auto-discovered endpoints-реестра.',
    '   */',
    '  interface CapsuleApi extends InferApi<Endpoints> {}',
    '}',
    'export {};',
    '',
  ].join('\n');

interface IProps {
  /** Куда писать runtime-registry. Обычно `<capsuleRoot>/registry/endpoints.ts`. */
  out: string;
  /** Куда писать .d.ts с глобальным `CapsuleApi`. */
  typesOut: string;
  /** Корень для скана: `apps/<app>/src`. */
  watchDir: string;
}

/**
 * Сканирует `apps/<app>/src/endpoints/**` и поддерживает в актуальном состоянии:
 *  - runtime-файл с namespace-tree (`endpoints` + тип `Endpoints`);
 *  - .d.ts с глобальным `CapsuleApi` (для типизации `services.api` в Feature).
 *
 * Зеркало структуры файлов:
 *  - `endpoints/user.ts`           → `endpoints.user`
 *  - `endpoints/user/index.ts`     → `endpoints.user`
 *  - `endpoints/admin/users.ts`    → `endpoints.admin.users`
 */
export const EndpointsRegistryPlugin = ({ out, typesOut, watchDir }: IProps): Plugin => {
  const known = new Map<string, Leaf>();
  let needsFlush = false;

  const srcRelFromRegistry = (() => {
    // out: <root>/.capsule/registry/endpoints.ts
    // watchDir: <root>/src
    // нужен относительный путь от dirname(out) к watchDir
    return relative(dirname(out), watchDir).split(/[\\/]/).join('/') || '.';
  })();

  const flush = () => {
    if (!needsFlush) return;
    needsFlush = false;
    const leaves = [...known.values()].sort((a, b) =>
      a.segments.join('/').localeCompare(b.segments.join('/')),
    );
    writeOut(out, renderRuntime(leaves, srcRelFromRegistry));
    writeOut(typesOut, renderTypes());
  };

  const handleEvent = (event: string, file: string, watchRoot: string) => {
    const leaf = fileToLeaf(file, watchRoot);
    if (!leaf) return;
    const key = leaf.segments.join('/');
    if (event === 'add' || event === 'addDir') {
      known.set(key, leaf);
    } else if (event === 'unlink' || event === 'unlinkDir') {
      known.delete(key);
    }
    needsFlush = true;
  };

  return {
    name: 'endpoints-registry',
    async buildStart() {
      const absWatch = resolve(watchDir);
      for (const file of await walkFiles(absWatch)) handleEvent('add', file, absWatch);
      // Эмитим даже если known пустой — нужен валидный пустой registry.
      needsFlush = true;
      flush();
    },
    async configureServer(server: ViteDevServer) {
      const absWatch = resolve(server.config.root, watchDir);
      for (const file of await walkFiles(absWatch)) handleEvent('add', file, absWatch);
      needsFlush = true;
      flush();

      watcherManager.init(server, absWatch);
      watcherManager.subscribe(absWatch, {
        onStructureChange: (event, paths) => {
          handleEvent(event, paths.file, absWatch);
          flush();
        },
      });
    },
  };
};
