import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { names } from '@nx/devkit';
import type { Plugin, ViteDevServer } from 'vite';
import { walkFiles, watcherManager } from '../utils';
import { EAGER_IMPORT_LAYERS, LAYER_TO_NAMESPACE } from './constants';

interface Leaf {
  /** Layer dir-key: `widgets` | `views` | `controllers` | `features`. */
  layer: string;
  /** Импорт-путь, например `@widgets/forms/_auth`. */
  importPath: string;
  /** Сегменты пути после layer'а в PascalCase: `['Forms', 'Auth']`, `['Viewer', 'LoginForm']`. */
  segments: string[];
}

interface TreeNode {
  children: Map<string, TreeNode>;
  leaf?: Leaf;
}

/** Один сегмент пути → PascalCase. У последнего отрезается расширение. */
const segmentToPascal = (seg: string, isLast: boolean): string => {
  const cleaned = isLast ? seg.replace(/\.[^/.]+$/, '') : seg;
  return names(cleaned).className;
};

const writeOut = (path: string, content: string) => {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf-8');
};

const fileToLeaf = (file: string, watchRoot: string, layers: readonly string[]): Leaf | null => {
  const rel = relative(watchRoot, file).split(/[\\/]/).filter(Boolean);
  const [layerDir, ...rest] = rel;
  if (!layers.includes(layerDir)) return null;
  if (rest.length === 0) return null;
  // Skip dot-files like `.gitkeep` (placeholders to keep empty layer dirs in
  // git). Any segment starting with `.` means a hidden / non-artifact file.
  if (rest.some((seg) => seg.startsWith('.'))) return null;

  const importPath = `@${layerDir}/${rest.join('/')}`.replace(/\.[^/.]+$/, '');
  const segments = rest.map((seg, i) => segmentToPascal(seg, i === rest.length - 1));
  return { layer: layerDir, importPath, segments };
};

const buildTree = (leaves: Leaf[]): TreeNode => {
  const root: TreeNode = { children: new Map() };
  for (const leaf of leaves) {
    let node = root;
    for (const seg of leaf.segments) {
      let child = node.children.get(seg);
      if (!child) {
        child = { children: new Map() };
        node.children.set(seg, child);
      }
      node = child;
    }
    node.leaf = leaf;
  }
  return root;
};

/**
 * Рекурсивно рендерит runtime-узел дерева.
 *
 * Если `eager = true` (слои типа `entities`):
 *   Лист → имя переменной eager-import'а (импорт объявляется наверху файла).
 * Иначе (component-слои):
 *   Лист → `lazy(...) as unknown as typeof import(...).default`.
 * Промежуточный → `{ Key: ... }`.
 */
const renderRuntimeNode = (node: TreeNode, indent: string, eager: boolean): string => {
  if (node.leaf && node.children.size === 0) {
    const { importPath, segments } = node.leaf;
    if (eager) {
      // Имя переменной: последний сегмент — уже PascalCase.
      return `_${segments.join('_')}`;
    }
    return `lazy(() => import('${importPath}')) as unknown as typeof import('${importPath}').default`;
  }
  const childIndent = `${indent}  `;
  const keys = [...node.children.keys()].sort();
  const entries = keys
    .map(
      (key) =>
        `${childIndent}${key}: ${renderRuntimeNode(node.children.get(key)!, childIndent, eager)}`,
    )
    .join(',\n');
  return `{\n${entries}\n${indent}}`;
};

/**
 * Рекурсивно рендерит type-узел дерева.
 * Лист → `typeof import(...).default`.
 * Промежуточный → `{ Key: ...; }`.
 */
const renderTypeNode = (node: TreeNode, indent: string): string => {
  if (node.leaf && node.children.size === 0) {
    return `typeof import('${node.leaf.importPath}').default`;
  }
  const childIndent = `${indent}  `;
  const keys = [...node.children.keys()].sort();
  const props = keys
    .map((key) => `${childIndent}${key}: ${renderTypeNode(node.children.get(key)!, childIndent)};`)
    .join('\n');
  return `{\n${props}\n${indent}}`;
};

/** Рантайм-файл: per-layer объект со ссылками на экспорты модулей. */
const renderRuntime = (leaves: Leaf[]): string => {
  const header: string[] = [
    '// generated by ExportGeneratorPlugin — не редактировать руками',
    "import { lazy } from 'solid-js';",
    '',
  ];

  // Eager import-строки накапливаем отдельно и вставляем после заголовка.
  const eagerImports: string[] = [];
  const body: string[] = [];

  const byLayer: Record<string, Leaf[]> = {};
  for (const leaf of leaves) {
    if (!byLayer[leaf.layer]) byLayer[leaf.layer] = [];
    byLayer[leaf.layer].push(leaf);
  }

  // Эмитим ВСЕ слои, даже пустые: иначе wrapper-сигнатура
  // `Widget((Ui, Features, Controllers, Views, Shapes) => …)` упадёт с
  // `Shapes is not defined`, когда у app'а нет ни одного shape-файла.
  const layerOrder = Object.keys(LAYER_TO_NAMESPACE);
  const namespaces: string[] = [];
  for (const layer of layerOrder) {
    const namespace =
      LAYER_TO_NAMESPACE[layer as keyof typeof LAYER_TO_NAMESPACE] ?? names(layer).className;
    namespaces.push(namespace);
    const layerLeaves = byLayer[layer] ?? [];
    const isEager = EAGER_IMPORT_LAYERS.has(layer);

    if (layerLeaves.length === 0) {
      body.push(`export const ${namespace} = {};`);
      body.push('');
      continue;
    }

    if (isEager) {
      // Для eager-слоёв (entities) генерируем именованные import'ы наверху файла.
      for (const leaf of layerLeaves) {
        const varName = `_${leaf.segments.join('_')}`;
        eagerImports.push(`import ${varName} from '${leaf.importPath}';`);
      }
    }

    const tree = buildTree(layerLeaves);
    const childIndent = '  ';
    const keys = [...tree.children.keys()].sort();
    const entries = keys
      .map(
        (key) =>
          `${childIndent}${key}: ${renderRuntimeNode(tree.children.get(key)!, childIndent, isEager)}`,
      )
      .join(',\n');
    body.push(`export const ${namespace} = {\n${entries}\n};`);
    body.push('');
  }

  // Top-level side-effect: populate globalThis synchronously on module eval.
  // This ensures Entities/Widgets/etc are available before any transitive
  // import (endpoints → features → widgets → pages → routeTree) accesses them.
  // bootstrap.tsx imports this module as a bare side-effect import and relies
  // on this assignment having fired before routeTree evaluation.
  const namespaceList = namespaces.join(', ');
  body.push(`Object.assign(globalThis, { ${namespaceList} });`);
  body.push('');

  const parts = [...header];
  if (eagerImports.length > 0) {
    parts.push(...eagerImports, '');
  }
  parts.push(...body);
  return parts.join('\n');
};

/**
 * Типизация: `declare global { interface Widgets {...}; interface Entities {...}; ... }`.
 *
 * Используются именно `interface` (а не `type`-алиасы), чтобы:
 *  1. Сливаться с пустыми fallback-интерфейсами в `@capsuletech/core` через interface merging.
 *  2. IDE показывала имя интерфейса (`Widgets`) в tooltip'ах вместо раскрытой структуры.
 *
 * Каждое поле-лист — `typeof import('@...').default`; для Ctrl+Click IDE предложит
 * Go-to-Implementation чтобы перейти в исходник.
 */
const renderTypes = (leaves: Leaf[]): string => {
  const lines: string[] = [
    '// generated by ExportGeneratorPlugin — не редактировать руками',
    'declare global {',
  ];

  const byLayer: Record<string, Leaf[]> = {};
  for (const leaf of leaves) {
    if (!byLayer[leaf.layer]) byLayer[leaf.layer] = [];
    byLayer[leaf.layer].push(leaf);
  }

  // Эмитим интерфейс ДЛЯ КАЖДОГО слоя, даже пустого: иначе interface merging
  // в `@capsuletech/core` сломается и `Controllers`/`Shapes` будут `unknown`.
  const layerOrder = Object.keys(LAYER_TO_NAMESPACE);
  for (const layer of layerOrder) {
    const namespace =
      LAYER_TO_NAMESPACE[layer as keyof typeof LAYER_TO_NAMESPACE] ?? names(layer).className;
    const layerLeaves = byLayer[layer] ?? [];
    if (layerLeaves.length === 0) {
      lines.push(`  interface ${namespace} {}`);
      continue;
    }
    const tree = buildTree(layerLeaves);
    const childIndent = '    ';
    const keys = [...tree.children.keys()].sort();
    const props = keys
      .map(
        (key) => `${childIndent}${key}: ${renderTypeNode(tree.children.get(key)!, childIndent)};`,
      )
      .join('\n');
    lines.push(`  interface ${namespace} {`);
    lines.push(props);
    lines.push('  }');
  }

  lines.push('}');
  lines.push('export {};');
  lines.push('');
  return lines.join('\n');
};

interface IProps {
  /** Куда писать runtime-файл со slot-объектами (lazy). */
  out: string;
  /** Куда писать .d.ts с augmentation'ом slot-интерфейсов. */
  typesOut: string;
  /** Корень для скана: обычно `apps/<app>/src`. */
  watchDir: string;
  /** Доп. layer-папки, если есть. */
  files?: Array<string>;
}

export const ExportGeneratorPlugin = ({ out, typesOut, watchDir, files = [] }: IProps): Plugin => {
  const layers = [...Object.keys(LAYER_TO_NAMESPACE), ...files];
  const known = new Map<string, Leaf>();
  let needsFlush = false;
  let scanned = false;

  const flush = () => {
    if (!needsFlush) return;
    needsFlush = false;
    const leaves = [...known.values()].sort((a, b) => {
      if (a.layer !== b.layer) return a.layer.localeCompare(b.layer);
      return a.segments.join('/').localeCompare(b.segments.join('/'));
    });
    writeOut(out, renderRuntime(leaves));
    writeOut(typesOut, renderTypes(leaves));
  };

  const handleEvent = (event: string, file: string, watchRoot: string) => {
    const leaf = fileToLeaf(file, watchRoot, layers);
    if (!leaf) return;
    const key = `${leaf.layer}::${leaf.segments.join('/')}`;
    if (event === 'add' || event === 'addDir') {
      known.set(key, leaf);
    } else if (event === 'unlink' || event === 'unlinkDir') {
      known.delete(key);
    }
    needsFlush = true;
  };

  // Initial-scan идемпотентен: `buildStart` дёргается и в dev, и в prod, а
  // `configureServer` — только в dev. Раньше скан проходил дважды в dev;
  // флаг `scanned` гарантирует, что walk файлов и flush выполняются один раз.
  const initialScan = async (absWatch: string) => {
    if (scanned) return;
    scanned = true;
    for (const file of await walkFiles(absWatch)) {
      handleEvent('add', file, absWatch);
    }
    flush();
  };

  return {
    name: 'export-generator',
    async buildStart() {
      await initialScan(resolve(watchDir));
    },
    async configureServer(server: ViteDevServer) {
      const absWatch = resolve(server.config.root, watchDir);
      await initialScan(absWatch);

      watcherManager.init(server, absWatch);
      watcherManager.subscribe(absWatch, {
        onStructureChange: (event, paths) => {
          handleEvent(event, paths.file, absWatch);
          flush();
        },
      });
    },
  };
};
