import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { Plugin } from 'vite';

/**
 * RemoteManifestPlugin — makes every capsule-app a remote module automatically.
 *
 * ## What it does
 *
 * ### Dev (serve mode)
 *
 * 1. On `buildStart`: writes `.capsule/remote-entry.ts` — a stable entry point
 *    that bootstraps the app into an arbitrary DOM container. The file is always
 *    overwritten (idempotent, no mtime/diff logic).
 *
 * 2. `configureServer` middleware: serves `GET /capsule.manifest.json` from
 *    memory, derived from `<appRoot>/package.json` at request time. The manifest
 *    contains:
 *      { name, version, entry: "/remote-entry.ts" }
 *    where `name` is the package name with any `@scope/` prefix stripped.
 *
 * ### Build mode
 *
 * 3. On `generateBundle`: emits `capsule.manifest.json` into the output directory
 *    as a static asset, with `entry` pointing to the compiled remote-entry chunk.
 *
 * ## Design notes
 *
 * - `Bootstrap` is generated by `CapsuleRegistryPlugin` into `.capsule/bootstrap.tsx`;
 *   `remote-entry.ts` lives as a sibling in `.capsule/` and imports it with a
 *   relative path (`./bootstrap`).
 * - No app-level config changes needed — the plugin is wired in `capsuleConfig.ts`
 *   alongside `EnsureScaffoldPlugin`.
 * - `@capsuletech/web-core/create` provides `createRoot`; it is already part of
 *   the framework runtime and available in every capsule-app.
 *
 * Ref: ADR-053 app-as-remote, manifest-driven discovery.
 */
export const RemoteManifestPlugin = (opts: { appRoot: string }): Plugin => {
  let capsuleRoot = '';
  let remoteEntryPath = '';

  return {
    name: 'capsule:remote-manifest',
    enforce: 'pre',

    configResolved(config) {
      // config.root is set to `<appRoot>/.capsule/` by capsuleConfig.
      capsuleRoot = config.root;
      remoteEntryPath = join(capsuleRoot, 'remote-entry.ts');
    },

    // P1: write `.capsule/remote-entry.ts` on every (re)start.
    buildStart() {
      const content = [
        "import { createRoot } from '@capsuletech/web-core/create';",
        "import { Bootstrap } from './bootstrap';",
        '',
        'export const bootstrap = (root: HTMLElement) => {',
        '  return createRoot(Bootstrap, { container: root });',
        '};',
        '',
      ].join('\n');

      mkdirSync(dirname(remoteEntryPath), { recursive: true });
      writeFileSync(remoteEntryPath, content, 'utf-8');
    },

    // P1: serve `/capsule.manifest.json` in dev.
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url !== '/capsule.manifest.json') return next();

        let pkg: { name?: string; version?: string } = {};
        try {
          pkg = JSON.parse(readFileSync(join(opts.appRoot, 'package.json'), 'utf-8'));
        } catch {
          // package.json unreadable — emit minimal manifest rather than 500.
          pkg = {};
        }

        // Strip `@scope/` prefix: "@capsuletech/my-app" -> "my-app".
        const rawName = pkg.name ?? '';
        const name = rawName.includes('/') ? rawName.split('/').pop()! : rawName;

        const manifest = {
          name,
          version: pkg.version ?? '0.0.0',
          entry: '/remote-entry.ts',
        };

        const body = JSON.stringify(manifest, null, 2);
        res.writeHead(200, {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
        });
        res.end(body);
      });
    },

    // P2: emit `capsule.manifest.json` into dist on build.
    generateBundle(_options, bundle) {
      let pkg: { name?: string; version?: string } = {};
      try {
        pkg = JSON.parse(readFileSync(join(opts.appRoot, 'package.json'), 'utf-8'));
      } catch {
        pkg = {};
      }

      const rawName = pkg.name ?? '';
      const name = rawName.includes('/') ? rawName.split('/').pop()! : rawName;

      // Find the compiled chunk that corresponds to remote-entry.ts.
      // Rollup preserves the base name as the chunk fileName for explicit entries.
      const entryChunk = Object.values(bundle).find(
        (chunk) =>
          chunk.type === 'chunk' &&
          chunk.isEntry &&
          (chunk.facadeModuleId?.endsWith('remote-entry.ts') ||
            chunk.name === 'remote-entry'),
      );

      const entry = entryChunk ? `/${entryChunk.fileName}` : '/remote-entry.js';

      const manifest = {
        name,
        version: pkg.version ?? '0.0.0',
        entry,
      };

      this.emitFile({
        type: 'asset',
        fileName: 'capsule.manifest.json',
        source: JSON.stringify(manifest, null, 2),
      });
    },
  };
};
