import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { Plugin } from 'vite';

// ─────────────────────────────────────────────────────────────────────────────
// ⚠️ RETIRE WITH ADR 059 / Brief 3 (web-remote → iframe-src).
//
// This whole plugin (`remote-entry.ts` generation + `capsule.manifest.json`)
// belongs to the OLD srcdoc/boot embedding model. ADR 059 D1/D5 replaces it
// with self-contained iframe-src: host loads the app's real URL, app mounts
// itself via the embed-aware `index.ts` entry (generateIndexEntry), config flows
// over postMessage. The manifest's `entry`-as-bundle is then dead — host needs
// only URL + query + postMessage.
//
// NOT removed in Brief 2: the current host (web-remote on main, srcdoc/boot)
// still fetches the manifest + imports `remote-entry.ts`, which imports
// `{ Bootstrap } from './bootstrap'`. Removing this before the host moves to
// iframe-src would break embedding. Delete this plugin + `remote-entry.ts` gen
// + the kept `Bootstrap` export together with Brief 3.
// ─────────────────────────────────────────────────────────────────────────────
export const RemoteManifestPlugin = (opts: { appRoot: string }): Plugin => {
  let capsuleRoot = '';
  let remoteEntryPath = '';

  return {
    name: 'capsule:remote-manifest',
    enforce: 'pre',

    configResolved(config) {
      capsuleRoot = config.root;
      remoteEntryPath = join(capsuleRoot, 'remote-entry.ts');
    },

    buildStart() {
      const userRemotePath = join(opts.appRoot, 'src', 'remote.ts');
      const hasUserRemote = existsSync(userRemotePath);
      const content = hasUserRemote ? buildUserAwareEntry() : buildDefaultEntry();
      mkdirSync(dirname(remoteEntryPath), { recursive: true });
      writeFileSync(remoteEntryPath, content, 'utf-8');
    },

    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url !== '/capsule.manifest.json') return next();
        let pkg: { name?: string; version?: string } = {};
        try {
          pkg = JSON.parse(readFileSync(join(opts.appRoot, 'package.json'), 'utf-8'));
        } catch {
          pkg = {};
        }
        const rawName = pkg.name ?? '';
        const name = rawName.includes('/') ? rawName.split('/').pop()! : rawName;
        const manifest = { name, version: pkg.version ?? '0.0.0', entry: '/remote-entry.ts' };
        const body = JSON.stringify(manifest, null, 2);
        res.writeHead(200, {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
        });
        res.end(body);
      });
    },

    generateBundle(_options, bundle) {
      let pkg: { name?: string; version?: string } = {};
      try {
        pkg = JSON.parse(readFileSync(join(opts.appRoot, 'package.json'), 'utf-8'));
      } catch {
        pkg = {};
      }
      const rawName = pkg.name ?? '';
      const name = rawName.includes('/') ? rawName.split('/').pop()! : rawName;
      const entryChunk = Object.values(bundle).find(
        (chunk) =>
          chunk.type === 'chunk' &&
          chunk.isEntry &&
          (chunk.facadeModuleId?.endsWith('remote-entry.ts') || chunk.name === 'remote-entry'),
      );
      const entry = entryChunk ? `/${entryChunk.fileName}` : '/remote-entry.js';
      const manifest = { name, version: pkg.version ?? '0.0.0', entry };
      this.emitFile({
        type: 'asset',
        fileName: 'capsule.manifest.json',
        source: JSON.stringify(manifest, null, 2),
      });
    },
  };
};

// Private helpers

function buildDefaultEntry(): string {
  return [
    '// auto-generated by RemoteManifestPlugin -- do not edit.',
    "import type { IRemoteBootstrap } from '@capsuletech/web-remote';",
    "import { createRoot } from '@capsuletech/web-core/create';",
    "import { Bootstrap } from './bootstrap';",
    '',
    'export const bootstrap: IRemoteBootstrap = (root, _ctx) => {',
    '  return createRoot(Bootstrap, { container: root });',
    '};',
    '',
  ].join('\n');
}

function buildUserAwareEntry(): string {
  return [
    '// auto-generated by RemoteManifestPlugin -- do not edit.',
    "import type { IRemoteBootstrap } from '@capsuletech/web-remote';",
    "import { createRoot } from '@capsuletech/web-core/create';",
    "import { Bootstrap } from './bootstrap';",
    "import * as user from '../src/remote';",
    '',
    'export const bootstrap: IRemoteBootstrap = (root, ctx) => {',
    '  const userBootstrap = (user as { bootstrap?: IRemoteBootstrap }).bootstrap;',
    "  if (typeof userBootstrap === 'function') {",
    '    return userBootstrap(root, ctx);',
    '  }',
    '  return createRoot(Bootstrap, { container: root });',
    '};',
    '',
  ].join('\n');
}
