import { existsSync } from 'node:fs';
import { copyFile, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TanStackRouterVite } from '@tanstack/router-vite-plugin';

import type { Plugin, ViteDevServer } from 'vite';

import { walkFiles, watcherManager } from '../../utils';

interface Paths {
  watchDir: string;
  outDir: string;
}

/**
 * Конвенция роутов (Capsule):
 *
 *   pages/index.tsx              → /                      (root index)
 *   pages/foo.tsx                → /foo                   (leaf)
 *   pages/foo/index.tsx          → /foo                   (layout + index: emit `routes/foo/route.tsx`)
 *   pages/foo/bar.tsx            → /foo/bar
 *   pages/foo/[id].tsx           → /foo/$id               (TanStack-param, при эмиссии [id] → $id)
 *   pages/foo/_group/bar.tsx     → /foo/bar               (`_group` — pathless, не в URL)
 *   pages/_pathless/baz.tsx      → /baz
 *
 * Файлы и папки, начинающиеся с `__` (дабл-андерскор), полностью игнорируются —
 * `__root.tsx` зарезервирован под framework root (ensureRootRoutePlugin), и
 * чтобы не путать пользователя «почему мой `__shared.tsx` стал роутом», мы
 * запрещаем дабл-андерскор как имя страницы.
 */
interface RouteInfo {
  /** URL для `createFileRoute('...')`, например `/foo/$id`. */
  routePath: string;
  /** Путь для lazy `import('@pages/...')`, без расширения, формат POSIX. */
  importPath: string;
  /** Относительный путь директории внутри `routes/` (POSIX), может быть пустым. */
  emitDir: string;
  /** Имя файла без расширения. */
  emitName: string;
}

const ROUTE_TEMPLATE = (info: RouteInfo) =>
  `// Auto-generated by @capsuletech/vite-builder router plugin. Do not edit.\n` +
  `import { lazy } from 'solid-js';\n` +
  `import { createFileRoute } from '@tanstack/solid-router';\n` +
  `\n` +
  `const Component = lazy(() => import('@pages/${info.importPath}') as Promise<{ default: any }>);\n` +
  `\n` +
  `export const Route = createFileRoute('${info.routePath}')({\n` +
  `  component: Component,\n` +
  `});\n`;

/**
 * Конвертит относительный путь `pages/...` в RouteInfo. Возвращает `null`, если
 * файл не должен порождать роут (private `__name`, не-tsx и т.п.).
 */
export const buildRouteInfo = (relativePath: string): RouteInfo | null => {
  if (!/\.tsx?$/.test(relativePath)) return null;

  const noExt = relativePath.replace(/\.tsx?$/, '');
  const segments = noExt.split(/[\\/]/);

  // Любой сегмент с `__` префиксом → файл/папка зарезервированы.
  if (segments.some((s) => s.startsWith('__'))) return null;

  const last = segments[segments.length - 1];
  const isIndex = last === 'index';

  // `[x]` → `$x`
  const toTanStackParam = (s: string) => s.replace(/^\[([^\]]+)\]$/, '$$$1');

  // URL: фильтруем `_`-сегменты (pathless), параметры разворачиваем в `$x`.
  const urlSourceSegments = isIndex ? segments.slice(0, -1) : segments;
  const urlSegments = urlSourceSegments.filter((s) => !s.startsWith('_')).map(toTanStackParam);
  const routePath = urlSegments.length === 0 ? '/' : `/${urlSegments.join('/')}`;

  // Emit: сохраняем `_`-сегменты (TanStack treats them as pathless layouts),
  // конвертим `[x]` → `$x`.
  const emitSourceSegments = isIndex ? segments.slice(0, -1) : segments;
  const emitSegments = emitSourceSegments.map(toTanStackParam);

  let emitDir = '';
  let emitName = '';
  if (isIndex) {
    if (segments.length === 1) {
      // pages/index.tsx → routes/index.tsx (TanStack root-index convention)
      emitDir = '';
      emitName = 'index';
    } else {
      // pages/foo/index.tsx → routes/foo/route.tsx (layout+index merged)
      emitDir = emitSegments.join('/');
      emitName = 'route';
    }
  } else {
    emitDir = emitSegments.slice(0, -1).join('/');
    emitName = emitSegments[emitSegments.length - 1];
  }

  // importPath: оригинальный путь под `@pages/`, в POSIX. `[id]` остаётся как есть —
  // Vite разрешает алиас в фактический файл, скобки в строковом литерале import()
  // допустимы. Если упрёмся — переключимся на относительные пути.
  const importPath = noExt.replace(/\\/g, '/');

  return { routePath, importPath, emitDir, emitName };
};

const fileGenerator = async (event: string, paths: Paths & { filePath: string }) => {
  const relativePath = relative(paths.watchDir, paths.filePath);
  if (!relativePath) return;
  const segments = relativePath.split(/[\\/]/);
  if (segments[0] !== 'pages') return;

  const insidePages = segments.slice(1).join('/');
  if (!insidePages) return;

  const isDirEvent = event.endsWith('Dir');
  if (isDirEvent) {
    // Папки сами по себе ничего не эмитят — ждём файлы внутри.
    // На unlinkDir нужно подчистить зеркало.
    if (event === 'unlinkDir') {
      // Удаляем зеркальный каталог в outDir (если есть), но с защитой
      // от удаления корня outDir.
      const mirrorDir = computeMirrorDir(paths.outDir, insidePages);
      const normalized = normalize(mirrorDir);
      const root = normalize(resolve(paths.outDir));
      if (normalized === root) return;
      await rm(mirrorDir, { recursive: true, force: true }).catch(() => {});
    }
    return;
  }

  const info = buildRouteInfo(insidePages);
  if (!info) {
    if (event === 'unlink') {
      // Файл удалён, но мы его и не эмитили (private/__). Ничего не делать.
    }
    return;
  }

  const targetDir = info.emitDir ? join(paths.outDir, info.emitDir) : paths.outDir;
  const targetFile = join(targetDir, `${info.emitName}.tsx`);

  try {
    if (event === 'add' || event === 'change') {
      await mkdir(targetDir, { recursive: true });
      await writeFile(targetFile, ROUTE_TEMPLATE(info), 'utf-8');
      console.log(`📄 Роут: ${info.routePath} → ${relative(paths.outDir, targetFile)}`);
    } else if (event === 'unlink') {
      const normalized = normalize(targetFile);
      const root = normalize(resolve(paths.outDir));
      if (normalized === root) return;
      await rm(targetFile, { force: true });
      console.log(`🗑️ Удалён роут: ${relative(paths.outDir, targetFile)}`);
    }
  } catch (e) {
    console.error(`[Generator] Error during ${event}:`, e);
  }
};

/**
 * Маппинг pages-каталога на зеркальный outDir-каталог с учётом transforms
 * (`[x]` → `$x`). Нужен для корректного `unlinkDir`.
 */
const computeMirrorDir = (outDir: string, insidePages: string): string => {
  const segments = insidePages.split(/[\\/]/).map((s) => s.replace(/^\[([^\]]+)\]$/, '$$$1'));
  return join(outDir, ...segments);
};

/**
 * Гарантирует наличие `__root.tsx` в routes-папке до того, как
 * TanStackRouterVite попробует прочитать её в `configResolved`.
 */
const ensureRootRoutePlugin = (outDir: string): Plugin => {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);

  return {
    name: 'capsule-ensure-root-route',
    enforce: 'pre',
    async config() {
      const absOutDir = resolve(outDir);
      const rootRoute = join(absOutDir, '__root.tsx');
      if (existsSync(rootRoute)) return;
      await mkdir(absOutDir, { recursive: true });
      await copyFile(resolve(__dirname, 'template', '__root.tsx.template'), rootRoute);
      console.log(`📄 Создан __root.tsx в ${absOutDir}`);
    },
  };
};

export const RouterPlugin = (paths: Paths): Array<Plugin> => {
  const GeneratorPlugin: Plugin = {
    name: 'capsule-route-generator',
    async configureServer(server: ViteDevServer) {
      const absolutePaths = {
        watchDir: resolve(server.config.root, paths.watchDir),
        outDir: resolve(server.config.root, paths.outDir),
      };

      // Initial scan: синхронизируем routes/ с pages/ до подписки на watcher.
      // chokidar стартует с ignoreInitial: true, иначе пропустим существующие файлы.
      const pagesDir = join(absolutePaths.watchDir, 'pages');
      if (existsSync(pagesDir)) {
        for (const file of await walkFiles(pagesDir)) {
          await fileGenerator('add', { ...absolutePaths, filePath: file });
        }
      }

      watcherManager.init(server, absolutePaths.watchDir);
      watcherManager.subscribe(absolutePaths.watchDir, {
        onStructureChange: async (event, { file: filePath }) => {
          await fileGenerator(event, { ...absolutePaths, filePath });
        },
      });
    },
  };

  return [
    ensureRootRoutePlugin(paths.outDir),
    GeneratorPlugin,
    TanStackRouterVite({
      target: 'solid',
      routesDirectory: paths.outDir,
      generatedRouteTree: join(paths.outDir, 'routeTree.gen.ts'),
    }) as unknown as Plugin,
  ];
};
