import { existsSync } from 'node:fs';
import { copyFile, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TanStackRouterVite } from '@tanstack/router-vite-plugin';

import type { Plugin, ViteDevServer } from 'vite';

import { walkFiles, watcherManager } from '../../utils';

interface Paths {
  watchDir: string;
  outDir: string;
  /**
   * Абсолютный путь к директории приложения (`apps/<name>/`).
   * Если задан, плагин проверяет наличие `src/features/app.tsx`:
   * при наличии — генерирует `__root.tsx` с mount-once `Features.App` wrapper'ом;
   * при отсутствии — генерирует стандартный `__root.tsx` с голым `<Outlet/>`.
   * При изменении `features/app.tsx` (add/unlink) `__root.tsx` регенерируется.
   */
  appRoot?: string;
}

/**
 * Конвенция роутов (Capsule):
 *
 *   pages/index.tsx              → /                      (root index)
 *   pages/foo.tsx                → /foo                   (leaf)
 *   pages/foo/index.tsx          → /foo                   (layout + index: emit `routes/foo/route.tsx`)
 *   pages/foo/bar.tsx            → /foo/bar
 *   pages/foo/[id].tsx           → /foo/$id               (TanStack-param, при эмиссии [id] → $id)
 *   pages/foo/_group/bar.tsx     → /foo/bar               (`_group` — pathless, не в URL)
 *   pages/_pathless/baz.tsx      → /baz
 *
 * Файлы и папки, начинающиеся с `__` (дабл-андерскор), полностью игнорируются —
 * `__root.tsx` зарезервирован под framework root (ensureRootRoutePlugin), и
 * чтобы не путать пользователя «почему мой `__shared.tsx` стал роутом», мы
 * запрещаем дабл-андерскор как имя страницы.
 */
interface RouteInfo {
  /** URL для `createFileRoute('...')`, например `/foo/$id`. */
  routePath: string;
  /** Путь для lazy `import('@pages/...')`, без расширения, формат POSIX. */
  importPath: string;
  /** Относительный путь директории внутри `routes/` (POSIX), может быть пустым. */
  emitDir: string;
  /** Имя файла без расширения. */
  emitName: string;
  /**
   * Если source — `<dir>/index.tsx` (directory layout), дополнительно генерим
   * `routes/<emitDir>/index.tsx` — index route с trailing slash (TanStack convention).
   * Значение — полный route path для index route, например `/_workspace/`.
   */
  indexRoutePath?: string;
}

export const ROUTE_TEMPLATE = (info: RouteInfo) =>
  `// Auto-generated by @capsuletech/vite-builder router plugin. Do not edit.\n` +
  `import { lazy } from 'solid-js';\n` +
  `import { createFileRoute, redirect } from '@tanstack/solid-router';\n` +
  `import { resolveAccess } from '@capsuletech/web-core';\n` +
  `\n` +
  `const Component = lazy(() => import('@pages/${info.importPath}') as Promise<{ default: any }>);\n` +
  `\n` +
  `export const Route = createFileRoute('${info.routePath}')({\n` +
  `  component: Component,\n` +
  `  beforeLoad: async () => {\n` +
  `    const mod: any = await import('@pages/${info.importPath}');\n` +
  `    const can: string | undefined = mod?.meta?.can;\n` +
  `    if (can && !resolveAccess(can)) throw redirect({ to: '/workspace' });\n` +
  `  },\n` +
  `});\n`;

/**
 * Index route passthrough для directory-layout.
 * TanStack Router: `createFileRoute('/_workspace/')` (trailing slash) = index child of layout.
 * Layout (route.tsx) рендерит `<Ui.Outlet/>` — при exact URL `/` Outlet матчит этот index
 * и рендерит пустоту, то есть user видит чистый layout без 404.
 */
const INDEX_ROUTE_TEMPLATE = (indexRoutePath: string) =>
  `// Auto-generated by @capsuletech/vite-builder router plugin. Do not edit.\n` +
  `import { createFileRoute } from '@tanstack/solid-router';\n` +
  `\n` +
  `export const Route = createFileRoute('${indexRoutePath}')({\n` +
  `  component: () => null,\n` +
  `});\n`;

/**
 * Index route с реальным компонентом — используется когда рядом с layout'ом
 * (`pages/<dir>/index.tsx`) присутствует файл `pages/<dir>/_index.tsx`.
 *
 * Конвенция: `_index.tsx` — TanStack-идиома opt-in fallback-контента для exact
 * URL сегмента (`/workspace/web-studio/`). Файл не порождает отдельный RouteInfo —
 * `buildRouteInfo` возвращает null для него. Вместо этого его наличие влияет на то,
 * какой template применяется к sibling `index.tsx` (layout).
 *
 * `importPath` — POSIX путь относительно `@pages/`, без расширения.
 * Например: `workspace/web-studio/_index`.
 */
export const INDEX_ROUTE_WITH_COMPONENT_TEMPLATE = (indexRoutePath: string, importPath: string) =>
  `// Auto-generated by @capsuletech/vite-builder router plugin. Do not edit.\n` +
  `import { lazy } from 'solid-js';\n` +
  `import { createFileRoute, redirect } from '@tanstack/solid-router';\n` +
  `import { resolveAccess } from '@capsuletech/web-core';\n` +
  `\n` +
  `const Component = lazy(() => import('@pages/${importPath}') as Promise<{ default: any }>);\n` +
  `\n` +
  `export const Route = createFileRoute('${indexRoutePath}')({\n` +
  `  component: Component,\n` +
  `  beforeLoad: async () => {\n` +
  `    const mod: any = await import('@pages/${importPath}');\n` +
  `    const can: string | undefined = mod?.meta?.can;\n` +
  `    if (can && !resolveAccess(can)) throw redirect({ to: '/workspace' });\n` +
  `  },\n` +
  `});\n`;

/**
 * Конвертит относительный путь `pages/...` в RouteInfo. Возвращает `null`, если
 * файл не должен порождать роут (private `__name`, не-tsx, `_index.tsx` и т.п.).
 */
export const buildRouteInfo = (relativePath: string): RouteInfo | null => {
  if (!/\.tsx?$/.test(relativePath)) return null;

  const noExt = relativePath.replace(/\.tsx?$/, '');
  const segments = noExt.split(/[\\/]/);

  // Любой сегмент с `__` префиксом → файл/папка зарезервированы.
  if (segments.some((s) => s.startsWith('__'))) return null;

  // `_index.tsx` — opt-in fallback для directory index-route.
  // Не порождает собственный RouteInfo — его наличие влияет только на sibling layout.
  // Top-level `pages/_index.tsx` тоже исключён — там другая семантика.
  if (segments[segments.length - 1] === '_index') return null;

  const last = segments[segments.length - 1];
  const isIndex = last === 'index';

  // `[x]` → `$x`
  const toTanStackParam = (s: string) => s.replace(/^\[([^\]]+)\]$/, '$$$1');

  // URL: фильтруем `_`-сегменты (pathless), параметры разворачиваем в `$x`.
  const urlSourceSegments = isIndex ? segments.slice(0, -1) : segments;
  const urlSegments = urlSourceSegments.filter((s) => !s.startsWith('_')).map(toTanStackParam);
  const routePath = urlSegments.length === 0 ? '/' : `/${urlSegments.join('/')}`;

  // Emit: сохраняем `_`-сегменты (TanStack treats them as pathless layouts),
  // конвертим `[x]` → `$x`.
  const emitSourceSegments = isIndex ? segments.slice(0, -1) : segments;
  const emitSegments = emitSourceSegments.map(toTanStackParam);

  let emitDir = '';
  let emitName = '';
  let indexRoutePath: string | undefined;

  if (isIndex) {
    if (segments.length === 1) {
      // pages/index.tsx → routes/index.tsx (TanStack root-index convention)
      emitDir = '';
      emitName = 'index';
    } else {
      // pages/foo/index.tsx → routes/foo/route.tsx (layout+index merged)
      emitDir = emitSegments.join('/');
      emitName = 'route';
      // Дополнительно генерим routes/foo/index.tsx — index route с trailing slash.
      // Путь включает все emitSegments (с `_`-префиксами — TanStack их понимает
      // как pathless layout-группы) + trailing `/`.
      indexRoutePath = `/${emitSegments.join('/')}/`;
    }
  } else {
    emitDir = emitSegments.slice(0, -1).join('/');
    emitName = emitSegments[emitSegments.length - 1];
  }

  // importPath: оригинальный путь под `@pages/`, в POSIX. `[id]` остаётся как есть —
  // Vite разрешает алиас в фактический файл, скобки в строковом литерале import()
  // допустимы. Если упрёмся — переключимся на относительные пути.
  const importPath = noExt.replace(/\\/g, '/');

  return { routePath, importPath, emitDir, emitName, indexRoutePath };
};

/**
 * Возвращает importPath для `_index.tsx` рядом с layout (`pages/<dir>/index.tsx`).
 * Принимает POSIX insidePages-путь до `index.tsx` layout'а.
 * Например: `workspace/web-studio/index.tsx` → `workspace/web-studio/_index`.
 */
const resolveIndexComponentImportPath = (insidePagesLayout: string): string => {
  const noExt = insidePagesLayout.replace(/\.tsx?$/, '');
  // noExt = 'workspace/web-studio/index' → dirname = 'workspace/web-studio'
  const parts = noExt.replace(/\\/g, '/').split('/');
  parts[parts.length - 1] = '_index';
  return parts.join('/');
};

/**
 * Для `_index.tsx`-файла триггерит регенерацию sibling index-route.
 * Если sibling `index.tsx` (layout) не найден — логируем и выходим.
 */
const regenerateSiblingIndexRoute = async (
  event: string,
  paths: Paths & { filePath: string },
  insidePages: string,
) => {
  // insidePages = '<dir>/_index.tsx' → sibling = '<dir>/index.tsx'
  const parts = insidePages.replace(/\\/g, '/').split('/');
  parts[parts.length - 1] = 'index.tsx';
  const siblingInsidePages = parts.join('/');

  const siblingAbsPath = join(paths.watchDir, 'pages', siblingInsidePages);
  if (!existsSync(siblingAbsPath)) {
    console.warn(
      `[capsule-router] _index.tsx without sibling index.tsx layout — ignored: ${insidePages}`,
    );
    return;
  }

  // Делегируем обработку sibling layout через fileGenerator с синтетическим событием.
  await fileGenerator(event === 'unlink' ? 'change' : event, {
    ...paths,
    filePath: siblingAbsPath,
  });
};

const fileGenerator = async (event: string, paths: Paths & { filePath: string }) => {
  const relativePath = relative(paths.watchDir, paths.filePath);
  if (!relativePath) return;
  const segments = relativePath.split(/[\\/]/);
  if (segments[0] !== 'pages') return;

  const insidePages = segments.slice(1).join('/');
  if (!insidePages) return;

  const isDirEvent = event.endsWith('Dir');
  if (isDirEvent) {
    // Папки сами по себе ничего не эмитят — ждём файлы внутри.
    // На unlinkDir нужно подчистить зеркало.
    if (event === 'unlinkDir') {
      // Удаляем зеркальный каталог в outDir (если есть), но с защитой
      // от удаления корня outDir.
      const mirrorDir = computeMirrorDir(paths.outDir, insidePages);
      const normalized = normalize(mirrorDir);
      const root = normalize(resolve(paths.outDir));
      if (normalized === root) return;
      await rm(mirrorDir, { recursive: true, force: true }).catch(() => {});
    }
    return;
  }

  // `_index.tsx` — не порождает роут сам, но влияет на sibling layout.
  const insidePagesNorm = insidePages.replace(/\\/g, '/');
  const insidePagesNoExt = insidePagesNorm.replace(/\.tsx?$/, '');
  const insidePagesBasename = insidePagesNoExt.split('/').pop();

  if (insidePagesBasename === '_index') {
    if (event === 'add' || event === 'change') {
      // Перегенерируем sibling layout → пишем index-route с компонентом.
      await regenerateSiblingIndexRoute(event, paths, insidePages);
    } else if (event === 'unlink') {
      // _index.tsx удалён → sibling layout возвращается к null-stub.
      // regenerateSiblingIndexRoute при event='unlink' шлёт 'change' → layout регенерируется
      // с existsSync(_index.tsx)=false → выберет INDEX_ROUTE_TEMPLATE.
      await regenerateSiblingIndexRoute(event, paths, insidePages);
    }
    return;
  }

  const info = buildRouteInfo(insidePages);
  if (!info) {
    // Файл удалён или private/__. Ничего не делать.
    return;
  }

  const targetDir = info.emitDir ? join(paths.outDir, info.emitDir) : paths.outDir;
  const targetFile = join(targetDir, `${info.emitName}.tsx`);

  try {
    if (event === 'add' || event === 'change') {
      await mkdir(targetDir, { recursive: true });
      await writeFile(targetFile, ROUTE_TEMPLATE(info), 'utf-8');
      console.log(
        `[capsule-router] route: ${info.routePath} → ${relative(paths.outDir, targetFile)}`,
      );

      // Directory index.tsx: дополнительно генерим index route.
      // Если рядом есть `_index.tsx` → lazy-компонент, иначе null stub.
      if (info.indexRoutePath) {
        const indexFile = join(targetDir, 'index.tsx');
        const siblingIndexComponentPath = join(dirname(paths.filePath), '_index.tsx');
        const hasFallback = existsSync(siblingIndexComponentPath);
        let indexContent: string;
        if (hasFallback) {
          const importPath = resolveIndexComponentImportPath(insidePagesNorm);
          indexContent = INDEX_ROUTE_WITH_COMPONENT_TEMPLATE(info.indexRoutePath, importPath);
          console.log(
            `[capsule-router] index route (with component): ${info.indexRoutePath} → ${relative(paths.outDir, indexFile)}`,
          );
        } else {
          indexContent = INDEX_ROUTE_TEMPLATE(info.indexRoutePath);
          console.log(
            `[capsule-router] index route (null stub): ${info.indexRoutePath} → ${relative(paths.outDir, indexFile)}`,
          );
        }
        await writeFile(indexFile, indexContent, 'utf-8');
      }
    } else if (event === 'unlink') {
      const normalized = normalize(targetFile);
      const root = normalize(resolve(paths.outDir));
      if (normalized === root) return;
      await rm(targetFile, { force: true });
      console.log(`[capsule-router] removed route: ${relative(paths.outDir, targetFile)}`);

      // Если удаляем layout (route.tsx) — убираем и сгенерированный index.
      if (info.indexRoutePath) {
        const indexFile = join(targetDir, 'index.tsx');
        await rm(indexFile, { force: true });
      }
    }
  } catch (e) {
    console.error(`[Generator] Error during ${event}:`, e);
  }
};

/**
 * Маппинг pages-каталога на зеркальный outDir-каталог с учётом transforms
 * (`[x]` → `$x`). Нужен для корректного `unlinkDir`.
 */
const computeMirrorDir = (outDir: string, insidePages: string): string => {
  const segments = insidePages.split(/[\\/]/).map((s) => s.replace(/^\[([^\]]+)\]$/, '$$$1'));
  return join(outDir, ...segments);
};

/**
 * Выполняет initial scan pages/ с правильным порядком:
 * сначала все `index.tsx` (layouts) — они эмитят route.tsx + index stub/component,
 * потом все остальные файлы (включая `_index.tsx`, которые тригерят sibling).
 *
 * Это гарантирует что при обработке `_index.tsx` sibling `index.tsx` уже обработан
 * (хотя логика `regenerateSiblingIndexRoute` всё равно делает existsSync — порядок
 * важен только для корректного финального состояния routes/).
 */
const initialPagesScan = async (
  pagesDir: string,
  absolutePaths: { watchDir: string; outDir: string },
): Promise<void> => {
  const allFiles = await walkFiles(pagesDir);
  const indexLayouts: string[] = [];
  const rest: string[] = [];
  for (const f of allFiles) {
    const base = f.replace(/\\/g, '/').split('/').pop() ?? '';
    if (base === 'index.tsx' || base === 'index.ts') {
      indexLayouts.push(f);
    } else {
      rest.push(f);
    }
  }
  for (const file of [...indexLayouts, ...rest]) {
    await fileGenerator('add', { ...absolutePaths, filePath: file });
  }
};

// ---------------------------------------------------------------------------
// Root route generation helpers
// ---------------------------------------------------------------------------

/**
 * Путь к `features/app.tsx` относительно appRoot.
 * Возвращает абсолютный путь к файлу.
 */
export const resolveAppFeaturePath = (appRoot: string): string =>
  join(appRoot, 'src', 'features', 'app.tsx');

/**
 * Генерирует содержимое `__root.tsx` с mount-once `<App>` wrapper'ом.
 *
 * `App` здесь — глобал из auto-import (`Features.App`), инжектируемый через
 * unplugin-auto-import. Но в сгенерированном `__root.tsx` нет доступа к
 * auto-import контексту, поэтому импортируем default-export напрямую из
 * `@features/app` — это корректный резолв через `paths.config.json` / AliasesPlugin.
 *
 * Семантика mount-once: TanStack Router гарантирует что root-route component
 * создаётся один раз и НЕ пересоздаётся при навигации. `<Outlet/>` свапает
 * только дочерний контент — сама `App`-фича остаётся живой.
 */
export const ROOT_WITH_APP_TEMPLATE = (): string =>
  [
    `// Auto-generated by @capsuletech/vite-builder router plugin. Do not edit.`,
    `// App-owned root feature detected: src/features/app.tsx`,
    `// Mount-once semantics: TanStack root-route renders once; only <Outlet/> swaps on navigation.`,
    `import App from '@features/app';`,
    `import { Outlet, createRootRouteWithContext } from '@tanstack/solid-router';`,
    ``,
    `interface MyRouterContext {`,
    `  isAuthenticated: boolean;`,
    `}`,
    ``,
    `export const Route = createRootRouteWithContext<MyRouterContext>()({`,
    `  component: () => (`,
    `    <App>`,
    `      <Outlet />`,
    `    </App>`,
    `  ),`,
    `});`,
    ``,
  ].join('\n');

/**
 * Записывает (или перезаписывает) `__root.tsx` в `outDir` в зависимости от
 * наличия `features/app.tsx` в appRoot.
 *
 * Экспортируется для тестирования.
 */
export const generateRootRoute = async (
  outDir: string,
  templateDir: string,
  appRoot: string | undefined,
): Promise<void> => {
  const absOutDir = resolve(outDir);
  await mkdir(absOutDir, { recursive: true });
  const rootRoute = join(absOutDir, '__root.tsx');

  const hasAppFeature = appRoot != null && existsSync(resolveAppFeaturePath(appRoot));

  if (hasAppFeature) {
    await writeFile(rootRoute, ROOT_WITH_APP_TEMPLATE(), 'utf-8');
    console.log(`[capsule-root-route] __root.tsx with Features.App generated`);
  } else {
    await copyFile(resolve(templateDir, '__root.tsx.template'), rootRoute);
    console.log(`[capsule-root-route] __root.tsx (plain Outlet) generated`);
  }
};

/**
 * Гарантирует наличие `__root.tsx` в routes-папке до того, как
 * TanStackRouterVite попробует прочитать её в `configResolved`.
 * При наличии `appRoot` и `src/features/app.tsx` — генерирует root с App wrapper'ом.
 * Всегда перегенерирует (не пропускает если уже существует), чтобы
 * add/remove `features/app.tsx` в dev-сессии корректно отражался.
 */
const ensureRootRoutePlugin = (outDir: string, appRoot: string | undefined): Plugin => {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);

  return {
    name: 'capsule-ensure-root-route',
    enforce: 'pre',
    async config() {
      await generateRootRoute(outDir, resolve(__dirname, 'template'), appRoot);
    },
  };
};

export const RouterPlugin = (paths: Paths): Array<Plugin> => {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const templateDir = resolve(__dirname, 'template');

  // Captured in configResolved; used by buildStart for build-mode page scan.
  let resolvedRoot = '';

  const GeneratorPlugin: Plugin = {
    name: 'capsule-route-generator',
    configResolved(config) {
      resolvedRoot = config.root;
    },
    async buildStart() {
      // Build mode: perform the same initial scan as configureServer.
      // configureServer only runs in dev; for `capsule build` we need routes
      // generated before TanStackRouterVite tries to read them.
      const absolutePaths = {
        watchDir: resolve(resolvedRoot, paths.watchDir),
        outDir: resolve(resolvedRoot, paths.outDir),
      };
      const pagesDir = join(absolutePaths.watchDir, 'pages');
      if (existsSync(pagesDir)) {
        await initialPagesScan(pagesDir, absolutePaths);
      }
    },
    async configureServer(server: ViteDevServer) {
      const absolutePaths = {
        watchDir: resolve(server.config.root, paths.watchDir),
        outDir: resolve(server.config.root, paths.outDir),
      };

      // Initial scan: синхронизируем routes/ с pages/ до подписки на watcher.
      // chokidar стартует с ignoreInitial: true, иначе пропустим существующие файлы.
      // Порядок: сначала index.tsx layouts, потом остальное (в т.ч. _index.tsx).
      const pagesDir = join(absolutePaths.watchDir, 'pages');
      if (existsSync(pagesDir)) {
        await initialPagesScan(pagesDir, absolutePaths);
      }

      watcherManager.init(server, absolutePaths.watchDir);
      watcherManager.subscribe(absolutePaths.watchDir, {
        onStructureChange: async (event, { file: filePath }) => {
          // Watch features/app.tsx: при add/unlink регенерируем __root.tsx.
          // Нормализуем разделители для кросс-платформенного сравнения.
          if (paths.appRoot != null) {
            const appFeaturePath = resolveAppFeaturePath(paths.appRoot);
            const normalizedFilePath = normalize(filePath);
            const normalizedFeaturePath = normalize(appFeaturePath);
            if (normalizedFilePath === normalizedFeaturePath) {
              if (event === 'add' || event === 'unlink') {
                await generateRootRoute(absolutePaths.outDir, templateDir, paths.appRoot);
              }
              return;
            }
          }

          await fileGenerator(event, { ...absolutePaths, filePath });
        },
      });
    },
  };

  return [
    ensureRootRoutePlugin(paths.outDir, paths.appRoot),
    GeneratorPlugin,
    TanStackRouterVite({
      target: 'solid',
      routesDirectory: paths.outDir,
      generatedRouteTree: join(paths.outDir, 'routeTree.gen.ts'),
    }) as unknown as Plugin,
  ];
};
