// generated by ExportGeneratorPlugin — не редактировать руками
import { lazy } from 'solid-js';

export const Widgets = {
  Welcome: lazy(() => import('@widgets/welcome')) as unknown as typeof import('@widgets/welcome').default
};

export const Entities = {
  Hello: lazy(() => import('@entities/hello')) as unknown as typeof import('@entities/hello').default
};

export const Controllers = {};

export const Features = {};

export const Shapes = {};
