/**
 * Unified per-primitive manifest schema for `@capsuletech/web-ui`.
 *
 * Canon: docs/_meta/web-ui.md section "Weight gradient & size manifest"
 *        + studio audit S2 (2026-06-13) — DnD rules + inspector fields
 *        merged here as single source of truth.
 *
 * Used by:
 *   - `scripts/build-manifest.mjs` — auto-generates bundle-cost fields
 *     (`name`, `subpath`, `weight`, `sizeKB`, `externals`, `variants`,
 *     `slotTags`); merges with hand-authored fields.
 *   - `packages/web/ui/test/bundle-size.test.ts` — bundle-size assertions
 *   - `@capsuletech/web-studio` palette + inspector + DnD validation
 *     (consumes via `@capsuletech/web-ui/manifest` subpath)
 *   - hand-authored manifest files in `src/manifest/manifests/*.tsx`
 *     populate the UI / DnD / inspector fields
 */

import type { ZodTypeAny } from '@capsuletech/shared-zod';
import type { JSX } from 'solid-js';

/**
 * Категория для группировки в палитре. Список закрыт намеренно — добавлять
 * новые категории сознательно, чтобы палитра не разрослась.
 */
export type ComponentCategory =
  | 'control' //      Button, Input, Checkbox, …
  | 'typography' //   Title, Text, Label
  | 'container' //    Grid, Flex, Group, List — структурные layout-контейнеры
  | 'composition' //  Card, Field — составные компонент-семейства с вложенными parts
  | 'composite' //    Card.Header, Field.Label — parts составных компонентов
  | 'feedback' //     Separator, Alert, Toast
  | 'wrapper'; //     Animate, Show, Suspense — non-visual обёртки

/**
 * Per-primitive manifest entry — unified shape covering bundle-cost +
 * UI metadata + DnD validation + inspector configuration.
 *
 * **Required fields (hand-authored)** define identity + UI behaviour:
 *   `type`, `label`, `category`, `icon`, `defaultProps`, `propsSchema`.
 *
 * **Optional fields auto-generated by `build-manifest.mjs`** at build time:
 *   `name`, `subpath`, `weight`, `sizeKB`, `externals`, `variants`,
 *   `slotTags`. Hand-authored manifests omit these; the build step
 *   merges them into the final `dist/manifest.json`.
 *
 * **Optional fields hand-authored** for DnD + inspector behaviour:
 *   `description`, `styleSlots`, `accepts`, `isLeaf`, `canBeRoot`.
 */
export interface IPrimitiveManifestEntry {
  // ─── Identity (hand-authored, required) ─────────────────────────────────
  /** Dot-path в registry — тот же ключ, что в JSON-схеме renderer'а. E.g. `'ui.Button'`, `'ui.Card.Header'`. */
  type: string;
  /** Человекочитаемое имя для палитры/инспектора (RU). E.g. `'Button'`, `'Card'`. */
  label: string;
  /** Категория для группировки в палитре. */
  category: ComponentCategory;

  // ─── UI metadata (hand-authored) ────────────────────────────────────────
  /** Render иконки — JSX (lucide-solid icon component или собственный SVG). */
  icon: () => JSX.Element;
  /** Короткое описание для tooltip'а в палитре. */
  description?: string;

  // ─── Inspector + create-node defaults (hand-authored, required) ─────────
  /**
   * Дефолтные пропсы при создании ноды. Должны валидироваться `propsSchema`.
   * Если в схеме есть `.default()`, можно дублировать здесь — это удобно
   * для IDE-навигации.
   */
  defaultProps: Record<string, unknown>;
  /** Zod-схема для инспектора (renderable форма). */
  propsSchema: ZodTypeAny;
  /**
   * Имена стилевых слотов, которые редактируемы. Дефолт — `['root']` (один
   * корневой). Для составных вроде Card можно `['root', 'header', 'footer']`.
   */
  styleSlots?: string[];

  // ─── DnD validation (hand-authored, optional) ───────────────────────────
  /**
   * Можно ли вкладывать `childType` внутрь этого компонента. Если не задано
   * и `isLeaf !== true` — принимает любого ребёнка. Если `isLeaf === true`,
   * `accepts` игнорируется и всегда false.
   */
  accepts?: (childType: string) => boolean;
  /** Leaf — детей быть не может. Drop в такой ноды запрещён. */
  isLeaf?: boolean;
  /**
   * Может ли компонент быть корнем в редакторе. По умолчанию любые containers
   * могут — UI-leaf не могут. Soft-rule, не enforced renderer'ом.
   */
  canBeRoot?: boolean;

  // ─── Docs wiring (optional, hand-authored) ──────────────────────────────
  /**
   * Slug в docs registry — путь к README этого компонента в формате
   * '<pkg-short>/<...path>/<unit>' (см. docs-system.md §5.1 — slug derivation).
   *
   * Studio info-panel → ReadmeBlock дёргает `<DocSection slug={manifest.docSlug}/>`.
   * Optional: примитивы без README просто не показывают док-блок.
   *
   * Example: `'web-ui/primitives/button'`
   */
  docSlug?: string;

  // ─── Bundle-cost (auto-generated by build-manifest.mjs) ─────────────────
  /** Primitive display name (lowercase subpath segment), e.g. 'button'. Auto-derived. */
  name?: string;
  /** Subpath import string, e.g. '@capsuletech/web-ui/button'. Auto-derived. */
  subpath?: string;
  /**
   * Weight category — UX tag for narrative / filter (not real cost — see `sizeKB`).
   *   L0 — presentational + native controls (no Kobalte interactive).
   *   L1 — interactive with a11y-pattern overhead.
   * Auto-classified per subpath in `build-manifest.mjs`.
   */
  weight?: 'L0' | 'L1';
  /** Real gzip cost (kB) measured at build time. */
  sizeKB?: number;
  /**
   * External deps remaining in graph after tree-shake. Consumer must supply
   * (peerDeps). Example: ['@kobalte/core/dropdown-menu', 'solid-js'].
   */
  externals?: string[];
  /**
   * Slot tags for UiProxy meta-routing.
   * Populated if the component exposes data-slot attributes.
   */
  slotTags?: string[];
  /**
   * CVA variant options available on the component.
   * Populated from CVA definitions for inspector dropdown.
   * Example: `{ variant: ['default', 'outline', 'ghost'], size: ['sm', 'default', 'lg'] }`
   */
  variants?: Record<string, string[]>;
}

/**
 * Built manifest entry — `IPrimitiveManifestEntry` with bundle-cost fields
 * narrowed to required. Returned by `scripts/build-manifest.mjs` after
 * merging hand-authored data with measured size/externals/variants.
 */
export type IBuiltManifestEntry = IPrimitiveManifestEntry &
  Required<
    Pick<
      IPrimitiveManifestEntry,
      'name' | 'subpath' | 'weight' | 'sizeKB' | 'externals'
    >
  >;

/** Root manifest shape emitted to dist/manifest.json. */
export interface IWebUiManifest {
  /** Semver of @capsuletech/web-ui that generated this manifest. */
  version: string;
  /** ISO timestamp of generation. */
  generatedAt: string;
  primitives: IBuiltManifestEntry[];
}

/**
 * Backwards-compat alias for studio consumers — pre-S2 they imported
 * `IComponentManifest` from `@capsuletech/web-studio/manifests`. After
 * unification, the canonical name is `IPrimitiveManifestEntry`.
 *
 * @deprecated use `IPrimitiveManifestEntry` directly.
 */
export type IComponentManifest = IPrimitiveManifestEntry;

/** Минимальная сводка манифеста для палитры (без `propsSchema`/`defaultProps`). */
export interface IManifestSummary {
  type: string;
  label: string;
  category: ComponentCategory;
  icon: () => JSX.Element;
  description?: string;
}
