/**
 * SubGenerator: registry/docs-sources.ts
 *
 * Generates:
 *   .capsule/registry/docs-sources.ts   (setDocsSources() call with lazy import map)
 *
 * Triggered by:
 *   - initial scan (forced flush — needs loaded appConfig)
 *   - capsule.app.ts change (onAppConfigChange — docs config may have changed)
 *
 * No src file events trigger this sub-gen; docs config comes from capsule.app.ts.
 *
 * If docs: field is absent entirely → cleanup (removeOut) if file previously existed.
 * If docs.rootVault / docs.packages are empty → same cleanup.
 *
 * order: 50 (after packages=40, before bootstrap=90)
 */

import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { readFileSync } from 'node:fs';
import type { CodegenContext, SubGenerator } from '../interfaces';

/** Output path relative to .capsule/ */
const DOCS_SOURCES_REL = 'registry/docs-sources.ts';

/**
 * Derives a short package identifier used as the key in the docs sources map.
 *
 * Rules:
 *   '@scope/name'  → 'name'   (strip @scope/ prefix)
 *   'name'         → 'name'   (no scope, used as-is)
 *
 * Examples:
 *   '@capsuletech/web-ui'  → 'web-ui'
 *   '@my-org/my-lib'       → 'my-lib'
 *   'some-lib'             → 'some-lib'
 */
export const derivePackageShort = (pkg: string): string => {
  if (pkg.startsWith('@')) {
    const scopeSep = pkg.indexOf('/', 1);
    if (scopeSep !== -1) {
      return pkg.slice(scopeSep + 1);
    }
  }
  return pkg;
};

/**
 * Checks whether a package has a "./docs.json" export in its package.json.
 *
 * Strategy:
 *  1. Try require.resolve('<pkg>/package.json') — works when package.json
 *     is listed in the package's exports map.
 *  2. Fallback: resolve the main entry of the package, then walk up the path
 *     to find the first package.json containing the expected package name.
 *
 * Reads package.json as raw JSON (no require() caching, no module execution).
 * Returns true if `exports['./docs.json']` is present.
 * Returns false (+ console.warn) on any resolution or parse error.
 */
export const checkDocsJsonExport = (pkg: string, appConfigDir: string): boolean => {
  const req = createRequire(resolve(appConfigDir, 'package.json'));

  // --- Attempt 1: resolve <pkg>/package.json directly ---
  let pkgJsonPath: string | null = null;
  try {
    pkgJsonPath = req.resolve(`${pkg}/package.json`);
  } catch {
    // Package may not list package.json in its exports — fall through.
  }

  // --- Attempt 2: walk up from main entry ---
  if (!pkgJsonPath) {
    try {
      const mainEntry = req.resolve(pkg).replace(/\\/g, '/');
      // Find last /node_modules/ boundary.
      const nmMarker = '/node_modules/';
      const nmIdx = mainEntry.lastIndexOf(nmMarker);
      if (nmIdx !== -1) {
        const afterNm = mainEntry.slice(nmIdx + nmMarker.length);
        const isScoped = afterNm.startsWith('@');
        const segments = afterNm.split('/');
        const pkgDirParts = isScoped ? segments.slice(0, 2) : segments.slice(0, 1);
        pkgJsonPath =
          mainEntry.slice(0, nmIdx + nmMarker.length) +
          pkgDirParts.join('/') +
          '/package.json';
      }
    } catch {
      // pass — pkgJsonPath remains null
    }
  }

  if (!pkgJsonPath) {
    console.warn(
      `[capsule:docs-sources] '${pkg}' has no "./docs.json" export, skipping`,
    );
    return false;
  }

  // --- Read package.json ---
  let pkgJson: Record<string, unknown>;
  try {
    pkgJson = JSON.parse(readFileSync(pkgJsonPath, 'utf-8')) as Record<string, unknown>;
  } catch {
    console.warn(
      `[capsule:docs-sources] could not read package.json for '${pkg}', skipping`,
    );
    return false;
  }

  const exports = pkgJson['exports'] as Record<string, unknown> | undefined;
  if (!exports?.['./docs.json']) {
    return false;
  }
  return true;
};

/**
 * Generates the content of .capsule/registry/docs-sources.ts.
 *
 * Stateless: (entries) => string.
 *
 * Each entry has a key (e.g. 'root', 'web-ui') and a pkg name.
 * The 'root' key is always from '@capsuletech/web-docs'.
 */
export const generateDocsSourcesRuntime = (
  entries: ReadonlyArray<{ key: string; pkg: string }>,
): string => {
  const lines: string[] = [
    '// Auto-generated by capsule-registry (docs-sources sub-generator).',
    '// Do not edit — regenerated on capsule.app.ts change.',
    "import { setDocsSources } from '@capsuletech/web-docs';",
    '',
    'setDocsSources({',
  ];

  for (const { key, pkg } of entries) {
    lines.push(`  ${JSON.stringify(key)}: () => import('${pkg}/docs.json'),`);
  }

  lines.push('});');
  lines.push('');
  return lines.join('\n');
};

export const createDocsSourcesSubGenerator = (): SubGenerator => {
  let dirty = false;
  /**
   * Tracks whether the last flush actually created the docs-sources file.
   * bootstrap() returns a contribution only when the file exists — otherwise
   * bootstrap.tsx would import a non-existent module.
   *
   * Starts as false (not yet flushed); becomes true after a successful write
   * and false again after removeOut.
   */
  let _hasFile = false;

  return {
    id: 'docs-sources',
    order: 50,

    match(_file: string): boolean {
      // Not triggered by src file events.
      return false;
    },

    onEvent(_ev, _file, _ctx): boolean {
      return false;
    },

    onAppConfigChange(_ctx: CodegenContext): boolean {
      dirty = true;
      return true;
    },

    flush(ctx, forced): void {
      if (!dirty && !forced) return;
      dirty = false;

      const outPath = resolve(ctx.capsuleRoot, DOCS_SOURCES_REL);
      const cfg = ctx.loadAppConfig();
      console.log('[capsule:docs-sources][debug] loadAppConfig keys:', cfg ? Object.keys(cfg) : 'undefined');
      console.log('[capsule:docs-sources][debug] cfg.docs:', JSON.stringify((cfg as { docs?: unknown })?.docs));
      const docs = cfg?.docs;

      // Cleanup: no docs config or nothing useful declared.
      if (
        !docs ||
        (docs.rootVault !== true && (!docs.packages || docs.packages.length === 0))
      ) {
        ctx.removeOut(outPath);
        _hasFile = false;
        return;
      }

      const appConfigDir = dirname(ctx.appConfigPath);
      const entries: Array<{ key: string; pkg: string }> = [];

      // Root vault entry — no export check needed (we own this package).
      if (docs.rootVault === true) {
        entries.push({ key: 'root', pkg: '@capsuletech/web-docs' });
      }

      // Per-package entries.
      for (const pkg of docs.packages ?? []) {
        if (!checkDocsJsonExport(pkg, appConfigDir)) {
          // checkDocsJsonExport already warned.
          continue;
        }
        entries.push({ key: derivePackageShort(pkg), pkg });
      }

      if (entries.length === 0) {
        // All packages skipped or everything empty — clean up.
        ctx.removeOut(outPath);
        _hasFile = false;
        return;
      }

      ctx.writeOut(outPath, generateDocsSourcesRuntime(entries));
      _hasFile = true;
    },

    bootstrap(_ctx): { phase: 'globals'; importPath: string } | null {
      // Only contribute when the file was actually generated.
      // If _hasFile is false (no docs config, or all packages skipped),
      // returning null prevents bootstrap.tsx from importing a non-existent module.
      if (!_hasFile) return null;
      return { phase: 'globals', importPath: './registry/docs-sources' };
    },
  };
};
