// generated by ExportGeneratorPlugin — не редактировать руками
import { lazy } from 'solid-js';

export const Widgets = {
  Chat: {
    Main: lazy(() => import('@widgets/chat/main')) as unknown as typeof import('@widgets/chat/main').default
  },
  Models: {
    Picker: lazy(() => import('@widgets/models/picker')) as unknown as typeof import('@widgets/models/picker').default
  }
};

export const Entities = {
  Chat: {
    Main: lazy(() => import('@entities/chat/main')) as unknown as typeof import('@entities/chat/main').default
  },
  Models: {
    Picker: lazy(() => import('@entities/models/picker')) as unknown as typeof import('@entities/models/picker').default
  }
};

export const Controllers = {
  Chat: {
    Main: lazy(() => import('@controllers/chat/main')) as unknown as typeof import('@controllers/chat/main').default
  },
  Models: {
    Picker: lazy(() => import('@controllers/models/picker')) as unknown as typeof import('@controllers/models/picker').default
  }
};

export const Features = {
  Chat: {
    Main: lazy(() => import('@features/chat/main')) as unknown as typeof import('@features/chat/main').default
  },
  Models: {
    Picker: lazy(() => import('@features/models/picker')) as unknown as typeof import('@features/models/picker').default
  }
};

export const Shapes = {};
