// generated by AppConfigPlugin — не редактировать руками
import { registerAliases } from '@capsuletech/web-state';
import { createApi, setApiClient } from '@capsuletech/web-query';
import appConfig from '../capsule.app';
import { endpoints } from './registry/endpoints';

registerAliases({});

if (appConfig.api) {
  setApiClient(createApi(appConfig.api, endpoints));
}
