/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as Home_rootRouteImport } from './home/__root'
import { Route as Demos_rootRouteImport } from './demos/__root'
import { Route as AuthRouteImport } from './auth'
import { Route as HomeRouteRouteImport } from './home/route'
import { Route as DemosRouteRouteImport } from './demos/route'
import { Route as HomeConfigsRouteImport } from './home/configs'
import { Route as HomeBranchesRouteImport } from './home/branches'
import { Route as HomeAppsRouteImport } from './home/apps'
import { Route as DemosThemeEditorRouteImport } from './demos/theme-editor'
import { Route as DemosRendererDemoRouteImport } from './demos/renderer-demo'
import { Route as DemosManifestsDemoRouteImport } from './demos/manifests-demo'
import { Route as DemosInspectorDemoRouteImport } from './demos/inspector-demo'
import { Route as DemosEditorStateDemoRouteImport } from './demos/editor-state-demo'
import { Route as DemosDndDemoRouteImport } from './demos/dnd-demo'

const Home_rootRoute = Home_rootRouteImport.update({
  id: '/__root',
  getParentRoute: () => HomeRouteRoute,
} as any)
const Demos_rootRoute = Demos_rootRouteImport.update({
  id: '/__root',
  getParentRoute: () => DemosRouteRoute,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRouteRoute = DemosRouteRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeConfigsRoute = HomeConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeBranchesRoute = HomeBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAppsRoute = HomeAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => HomeRouteRoute,
} as any)
const DemosThemeEditorRoute = DemosThemeEditorRouteImport.update({
  id: '/theme-editor',
  path: '/theme-editor',
  getParentRoute: () => DemosRouteRoute,
} as any)
const DemosRendererDemoRoute = DemosRendererDemoRouteImport.update({
  id: '/renderer-demo',
  path: '/renderer-demo',
  getParentRoute: () => DemosRouteRoute,
} as any)
const DemosManifestsDemoRoute = DemosManifestsDemoRouteImport.update({
  id: '/manifests-demo',
  path: '/manifests-demo',
  getParentRoute: () => DemosRouteRoute,
} as any)
const DemosInspectorDemoRoute = DemosInspectorDemoRouteImport.update({
  id: '/inspector-demo',
  path: '/inspector-demo',
  getParentRoute: () => DemosRouteRoute,
} as any)
const DemosEditorStateDemoRoute = DemosEditorStateDemoRouteImport.update({
  id: '/editor-state-demo',
  path: '/editor-state-demo',
  getParentRoute: () => DemosRouteRoute,
} as any)
const DemosDndDemoRoute = DemosDndDemoRouteImport.update({
  id: '/dnd-demo',
  path: '/dnd-demo',
  getParentRoute: () => DemosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/demos': typeof Demos_rootRoute
  '/home': typeof Home_rootRoute
  '/auth': typeof AuthRoute
  '/demos/dnd-demo': typeof DemosDndDemoRoute
  '/demos/editor-state-demo': typeof DemosEditorStateDemoRoute
  '/demos/inspector-demo': typeof DemosInspectorDemoRoute
  '/demos/manifests-demo': typeof DemosManifestsDemoRoute
  '/demos/renderer-demo': typeof DemosRendererDemoRoute
  '/demos/theme-editor': typeof DemosThemeEditorRoute
  '/home/apps': typeof HomeAppsRoute
  '/home/branches': typeof HomeBranchesRoute
  '/home/configs': typeof HomeConfigsRoute
}
export interface FileRoutesByTo {
  '/demos': typeof Demos_rootRoute
  '/home': typeof Home_rootRoute
  '/auth': typeof AuthRoute
  '/demos/dnd-demo': typeof DemosDndDemoRoute
  '/demos/editor-state-demo': typeof DemosEditorStateDemoRoute
  '/demos/inspector-demo': typeof DemosInspectorDemoRoute
  '/demos/manifests-demo': typeof DemosManifestsDemoRoute
  '/demos/renderer-demo': typeof DemosRendererDemoRoute
  '/demos/theme-editor': typeof DemosThemeEditorRoute
  '/home/apps': typeof HomeAppsRoute
  '/home/branches': typeof HomeBranchesRoute
  '/home/configs': typeof HomeConfigsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/demos': typeof DemosRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demos/__root': typeof Demos_rootRoute
  '/demos/dnd-demo': typeof DemosDndDemoRoute
  '/demos/editor-state-demo': typeof DemosEditorStateDemoRoute
  '/demos/inspector-demo': typeof DemosInspectorDemoRoute
  '/demos/manifests-demo': typeof DemosManifestsDemoRoute
  '/demos/renderer-demo': typeof DemosRendererDemoRoute
  '/demos/theme-editor': typeof DemosThemeEditorRoute
  '/home/__root': typeof Home_rootRoute
  '/home/apps': typeof HomeAppsRoute
  '/home/branches': typeof HomeBranchesRoute
  '/home/configs': typeof HomeConfigsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/demos'
    | '/home'
    | '/auth'
    | '/demos/dnd-demo'
    | '/demos/editor-state-demo'
    | '/demos/inspector-demo'
    | '/demos/manifests-demo'
    | '/demos/renderer-demo'
    | '/demos/theme-editor'
    | '/home/apps'
    | '/home/branches'
    | '/home/configs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demos'
    | '/home'
    | '/auth'
    | '/demos/dnd-demo'
    | '/demos/editor-state-demo'
    | '/demos/inspector-demo'
    | '/demos/manifests-demo'
    | '/demos/renderer-demo'
    | '/demos/theme-editor'
    | '/home/apps'
    | '/home/branches'
    | '/home/configs'
  id:
    | '__root__'
    | '/demos'
    | '/home'
    | '/auth'
    | '/demos/__root'
    | '/demos/dnd-demo'
    | '/demos/editor-state-demo'
    | '/demos/inspector-demo'
    | '/demos/manifests-demo'
    | '/demos/renderer-demo'
    | '/demos/theme-editor'
    | '/home/__root'
    | '/home/apps'
    | '/home/branches'
    | '/home/configs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DemosRouteRoute: typeof DemosRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/home/__root': {
      id: '/home/__root'
      path: ''
      fullPath: '/home'
      preLoaderRoute: typeof Home_rootRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/demos/__root': {
      id: '/demos/__root'
      path: ''
      fullPath: '/demos'
      preLoaderRoute: typeof Demos_rootRouteImport
      parentRoute: typeof DemosRouteRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/configs': {
      id: '/home/configs'
      path: '/configs'
      fullPath: '/home/configs'
      preLoaderRoute: typeof HomeConfigsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/branches': {
      id: '/home/branches'
      path: '/branches'
      fullPath: '/home/branches'
      preLoaderRoute: typeof HomeBranchesRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/apps': {
      id: '/home/apps'
      path: '/apps'
      fullPath: '/home/apps'
      preLoaderRoute: typeof HomeAppsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/demos/theme-editor': {
      id: '/demos/theme-editor'
      path: '/theme-editor'
      fullPath: '/demos/theme-editor'
      preLoaderRoute: typeof DemosThemeEditorRouteImport
      parentRoute: typeof DemosRouteRoute
    }
    '/demos/renderer-demo': {
      id: '/demos/renderer-demo'
      path: '/renderer-demo'
      fullPath: '/demos/renderer-demo'
      preLoaderRoute: typeof DemosRendererDemoRouteImport
      parentRoute: typeof DemosRouteRoute
    }
    '/demos/manifests-demo': {
      id: '/demos/manifests-demo'
      path: '/manifests-demo'
      fullPath: '/demos/manifests-demo'
      preLoaderRoute: typeof DemosManifestsDemoRouteImport
      parentRoute: typeof DemosRouteRoute
    }
    '/demos/inspector-demo': {
      id: '/demos/inspector-demo'
      path: '/inspector-demo'
      fullPath: '/demos/inspector-demo'
      preLoaderRoute: typeof DemosInspectorDemoRouteImport
      parentRoute: typeof DemosRouteRoute
    }
    '/demos/editor-state-demo': {
      id: '/demos/editor-state-demo'
      path: '/editor-state-demo'
      fullPath: '/demos/editor-state-demo'
      preLoaderRoute: typeof DemosEditorStateDemoRouteImport
      parentRoute: typeof DemosRouteRoute
    }
    '/demos/dnd-demo': {
      id: '/demos/dnd-demo'
      path: '/dnd-demo'
      fullPath: '/demos/dnd-demo'
      preLoaderRoute: typeof DemosDndDemoRouteImport
      parentRoute: typeof DemosRouteRoute
    }
  }
}

interface DemosRouteRouteChildren {
  Demos_rootRoute: typeof Demos_rootRoute
  DemosDndDemoRoute: typeof DemosDndDemoRoute
  DemosEditorStateDemoRoute: typeof DemosEditorStateDemoRoute
  DemosInspectorDemoRoute: typeof DemosInspectorDemoRoute
  DemosManifestsDemoRoute: typeof DemosManifestsDemoRoute
  DemosRendererDemoRoute: typeof DemosRendererDemoRoute
  DemosThemeEditorRoute: typeof DemosThemeEditorRoute
}

const DemosRouteRouteChildren: DemosRouteRouteChildren = {
  Demos_rootRoute: Demos_rootRoute,
  DemosDndDemoRoute: DemosDndDemoRoute,
  DemosEditorStateDemoRoute: DemosEditorStateDemoRoute,
  DemosInspectorDemoRoute: DemosInspectorDemoRoute,
  DemosManifestsDemoRoute: DemosManifestsDemoRoute,
  DemosRendererDemoRoute: DemosRendererDemoRoute,
  DemosThemeEditorRoute: DemosThemeEditorRoute,
}

const DemosRouteRouteWithChildren = DemosRouteRoute._addFileChildren(
  DemosRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  Home_rootRoute: typeof Home_rootRoute
  HomeAppsRoute: typeof HomeAppsRoute
  HomeBranchesRoute: typeof HomeBranchesRoute
  HomeConfigsRoute: typeof HomeConfigsRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  Home_rootRoute: Home_rootRoute,
  HomeAppsRoute: HomeAppsRoute,
  HomeBranchesRoute: HomeBranchesRoute,
  HomeConfigsRoute: HomeConfigsRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DemosRouteRoute: DemosRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
