/**
 * Tests for CapsuleRegistryPlugin sub-generators.
 *
 * Sub-generators are exported stateless functions, so they can be tested in
 * isolation without spinning up a Vite server or touching the filesystem.
 *
 * What is covered:
 *
 * ── Barrel registry (ADR-034) ─────────────────────────────────────────────────
 *  - generateRegistryIndex emits 'export * as Widgets from ...' for all layers.
 *  - generateRegistryPackageJson has sideEffects: false.
 *  - generateBarrelRegistry — flat leaf → leaf export { default as X }.
 *  - generateBarrelRegistry — nested leaf → intermediate export * as + leaf.
 *  - generateBarrelRegistry — empty layer → empty barrel (export {}).
 *  - generateBarrelRegistry — no lazy(), no globalThis.
 *  - generateBarrelRegistry — all 6 layer index files are present.
 *  - generateBarrelRegistry — registry/index.ts and package.json are present.
 *
 * ── Endpoints (generateEndpointsRuntime / generateEndpointsTypes) ────────────
 *  - Flat endpoint file → endpoints.user.
 *  - Nested endpoint file → endpoints.admin.users.
 *  - index.ts inside dir → correct segment without 'index'.
 *  - Empty endpoints/ → empty `endpoints = {}` (no crash).
 *  - Types file imports InferApi from correct package.
 *
 * ── AppConfig (generateAppConfigRuntime) ─────────────────────────────────────
 *  - Contains registerAliases, createApi, setApiClient.
 *  - Static endpoints import (not dynamic).
 *  - IAppConfig type-only import.
 *
 * ── Bootstrap (generateBootstrap) ────────────────────────────────────────────
 *  - packages (globals) imported before app-config (subsystems).
 *  - routeTree named import present.
 *  - styles.css and BaseProviders are present.
 *  - No wrappers side-effect import (ADR-034 — no globalThis assign).
 *  - No editable user content in the file.
 *
 * ── LAYER_INIT_ORDER contract ─────────────────────────────────────────────────
 *  - 'globals' phase comes before 'subsystems' which comes before 'render'.
 *  - No 'wrappers' entry (ADR-034).
 *  - 'packages' entry is phase 'globals'.
 *  - 'routes' entry is phase 'render'.
 *  - All entries have unique names.
 *
 * ── CapsuleRegistryPlugin transform ──────────────────────────────────────────
 *  - defineEndpoint injected into src/endpoints/** (enforce:'pre' transform).
 *  - defineEndpoint injection is idempotent.
 *  - defineEndpoint NOT injected outside endpoints/.
 *  - defineAppConfig replaced with identity-unwrap in capsule.app.ts.
 *  - defineAppConfig NOT replaced in unrelated files.
 */

import { join, resolve } from 'node:path';
import type { Plugin } from 'vite';
import { describe, expect, it } from 'vitest';
import {
  CapsuleRegistryPlugin,
  generateAppConfigRuntime,
  generateBarrelRegistry,
  generateBootstrap,
  generateEndpointsRuntime,
  generateEndpointsTypes,
  generatePackagesRuntime,
  generatePackagesTypes,
  generateRegistryIndex,
  generateRegistryPackageJson,
  LAYER_INIT_ORDER,
  parseManifestSource,
  type ResolvedPackageEntry,
  resolvePackageEntries,
} from '../capsuleRegistry';

// ---------------------------------------------------------------------------
// Helpers to build leaf objects without exercising FS
// ---------------------------------------------------------------------------

interface WrapperLeaf {
  layer: string;
  importPath: string;
  segments: string[];
}

interface EndpointLeaf {
  segments: string[];
  relPath: string;
}

const wrapperLeaf = (layer: string, importPath: string, segments: string[]): WrapperLeaf => ({
  layer,
  importPath,
  segments,
});

const endpointLeaf = (segments: string[], relPath: string): EndpointLeaf => ({
  segments,
  relPath,
});

// ---------------------------------------------------------------------------
// Barrel registry — generateRegistryIndex
// ---------------------------------------------------------------------------

describe('generateRegistryIndex', () => {
  it('emits export * as Widgets from ./widgets', () => {
    const out = generateRegistryIndex();
    expect(out).toContain("export * as Widgets from './widgets';");
  });

  it('emits all 6 namespaces', () => {
    const out = generateRegistryIndex();
    expect(out).toContain("export * as Widgets from './widgets';");
    expect(out).toContain("export * as Views from './views';");
    expect(out).toContain("export * as Controllers from './controllers';");
    expect(out).toContain("export * as Features from './features';");
    expect(out).toContain("export * as Shapes from './shapes';");
    expect(out).toContain("export * as Entities from './entities';");
  });

  it('starts with generated comment', () => {
    const out = generateRegistryIndex();
    expect(out.startsWith('// generated by CapsuleRegistryPlugin')).toBe(true);
  });

  it('does not contain Object.assign', () => {
    const out = generateRegistryIndex();
    expect(out).not.toContain('Object.assign');
  });

  it('does not contain globalThis', () => {
    const out = generateRegistryIndex();
    expect(out).not.toContain('globalThis');
  });
});

// ---------------------------------------------------------------------------
// Barrel registry — generateRegistryPackageJson
// ---------------------------------------------------------------------------

describe('generateRegistryPackageJson', () => {
  it('contains sideEffects: false', () => {
    const out = generateRegistryPackageJson();
    const parsed = JSON.parse(out);
    expect(parsed.sideEffects).toBe(false);
  });

  it('is valid JSON', () => {
    const out = generateRegistryPackageJson();
    expect(() => JSON.parse(out)).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Barrel registry — generateBarrelRegistry
// ---------------------------------------------------------------------------

describe('generateBarrelRegistry — widget leaf at 2-segment path (Forms/Auth)', () => {
  // ['Forms', 'Auth'] → leaf is Auth inside Forms dir (no deeper subdir)
  const leaf = wrapperLeaf('widgets', '@widgets/forms/auth', ['Forms', 'Auth']);

  it('generates registry/index.ts with export * as Widgets', () => {
    const files = generateBarrelRegistry([leaf]);
    const index = files.get('index.ts');
    expect(index).toBeDefined();
    expect(index).toContain("export * as Widgets from './widgets';");
  });

  it('generates widgets/index.ts with export * as Forms', () => {
    const files = generateBarrelRegistry([leaf]);
    const widgetsIndex = files.get('widgets/index.ts');
    expect(widgetsIndex).toBeDefined();
    expect(widgetsIndex).toContain("export * as Forms from './forms';");
  });

  it('generates widgets/forms/index.ts with leaf export { default as Auth }', () => {
    // Auth is a pure leaf (no children) — emitted directly in parent forms/index.ts
    const files = generateBarrelRegistry([leaf]);
    const formsIndex = files.get('widgets/forms/index.ts');
    expect(formsIndex).toBeDefined();
    expect(formsIndex).toContain("export { default as Auth } from '@widgets/forms/auth';");
  });

  it('does NOT emit lazy()', () => {
    const files = generateBarrelRegistry([leaf]);
    for (const content of files.values()) {
      expect(content).not.toContain('lazy(');
    }
  });

  it('does NOT emit Object.assign or globalThis', () => {
    const files = generateBarrelRegistry([leaf]);
    for (const content of files.values()) {
      expect(content).not.toContain('Object.assign');
      expect(content).not.toContain('globalThis');
    }
  });
});

describe('generateBarrelRegistry — widget leaf at 3-segment path (Forms/Auth/Login)', () => {
  // ['Forms', 'Auth', 'Login'] → subdir auth/ with leaf Login
  const leaf = wrapperLeaf('widgets', '@widgets/forms/auth/login', ['Forms', 'Auth', 'Login']);

  it('generates widgets/index.ts with export * as Forms', () => {
    const files = generateBarrelRegistry([leaf]);
    const widgetsIndex = files.get('widgets/index.ts');
    expect(widgetsIndex).toBeDefined();
    expect(widgetsIndex).toContain("export * as Forms from './forms';");
  });

  it('generates widgets/forms/index.ts with export * as Auth', () => {
    const files = generateBarrelRegistry([leaf]);
    const formsIndex = files.get('widgets/forms/index.ts');
    expect(formsIndex).toBeDefined();
    expect(formsIndex).toContain("export * as Auth from './auth';");
  });

  it('generates widgets/forms/auth/index.ts with leaf export { default as Login }', () => {
    const files = generateBarrelRegistry([leaf]);
    const authIndex = files.get('widgets/forms/auth/index.ts');
    expect(authIndex).toBeDefined();
    expect(authIndex).toContain("export { default as Login } from '@widgets/forms/auth/login';");
  });

  it('does NOT emit lazy()', () => {
    const files = generateBarrelRegistry([leaf]);
    for (const content of files.values()) {
      expect(content).not.toContain('lazy(');
    }
  });
});

describe('generateBarrelRegistry — flat entity leaf (no nesting)', () => {
  const leaf = wrapperLeaf('entities', '@entities/incident', ['Incident']);

  it('generates entities/index.ts with leaf export { default as Incident }', () => {
    const files = generateBarrelRegistry([leaf]);
    const entitiesIndex = files.get('entities/index.ts');
    expect(entitiesIndex).toBeDefined();
    expect(entitiesIndex).toContain("export { default as Incident } from '@entities/incident';");
  });

  it('does NOT emit lazy() for entities (no eager→lazy regression)', () => {
    const files = generateBarrelRegistry([leaf]);
    for (const content of files.values()) {
      expect(content).not.toContain('lazy(');
    }
  });
});

describe('generateBarrelRegistry — multiple leaves same subdir', () => {
  // 3-segment leaves: Forms/Auth/Login, Forms/Auth/Register → both in auth/index.ts
  const leaf1 = wrapperLeaf('widgets', '@widgets/forms/auth/login', ['Forms', 'Auth', 'Login']);
  const leaf2 = wrapperLeaf('widgets', '@widgets/forms/auth/register', ['Forms', 'Auth', 'Register']);

  it('both leaves appear in auth/index.ts', () => {
    const files = generateBarrelRegistry([leaf1, leaf2]);
    const authIndex = files.get('widgets/forms/auth/index.ts');
    expect(authIndex).toBeDefined();
    expect(authIndex).toContain("export { default as Login } from '@widgets/forms/auth/login';");
    expect(authIndex).toContain("export { default as Register } from '@widgets/forms/auth/register';");
  });

  it('forms/index.ts links to auth/ subdir via export * as Auth', () => {
    const files = generateBarrelRegistry([leaf1, leaf2]);
    const formsIndex = files.get('widgets/forms/index.ts');
    expect(formsIndex).toBeDefined();
    expect(formsIndex).toContain("export * as Auth from './auth';");
  });
});

describe('generateBarrelRegistry — empty layer', () => {
  it('emits export {} for empty layer', () => {
    const files = generateBarrelRegistry([]);
    const widgetsIndex = files.get('widgets/index.ts');
    expect(widgetsIndex).toBeDefined();
    expect(widgetsIndex).toContain('export {};');
  });

  it('still emits all 6 layer index files', () => {
    const files = generateBarrelRegistry([]);
    const layerDirs = ['widgets', 'views', 'controllers', 'features', 'shapes', 'entities'];
    for (const layer of layerDirs) {
      expect(files.has(`${layer}/index.ts`)).toBe(true);
    }
  });

  it('emits registry/index.ts even when empty', () => {
    const files = generateBarrelRegistry([]);
    expect(files.has('index.ts')).toBe(true);
  });

  it('emits registry/package.json even when empty', () => {
    const files = generateBarrelRegistry([]);
    expect(files.has('package.json')).toBe(true);
    const pkg = JSON.parse(files.get('package.json')!);
    expect(pkg.sideEffects).toBe(false);
  });
});

describe('generateBarrelRegistry — cross-layer leaves', () => {
  const widgetLeaf = wrapperLeaf('widgets', '@widgets/forms/auth', ['Forms', 'Auth']);
  const viewLeaf = wrapperLeaf('views', '@views/authFormCard', ['AuthFormCard']);
  const entityLeaf = wrapperLeaf('entities', '@entities/incident', ['Incident']);

  it('widgets and views appear in different layer index files', () => {
    const files = generateBarrelRegistry([widgetLeaf, viewLeaf, entityLeaf]);
    const widgetsIndex = files.get('widgets/index.ts');
    const viewsIndex = files.get('views/index.ts');
    const entitiesIndex = files.get('entities/index.ts');
    expect(widgetsIndex).toContain("export * as Forms from './forms';");
    expect(viewsIndex).toContain("export { default as AuthFormCard } from '@views/authFormCard';");
    expect(entitiesIndex).toContain("export { default as Incident } from '@entities/incident';");
  });

  it('registry/index.ts contains all 6 namespaces regardless of which are populated', () => {
    const files = generateBarrelRegistry([widgetLeaf]);
    const index = files.get('index.ts');
    expect(index).toContain("export * as Widgets from './widgets';");
    expect(index).toContain("export * as Views from './views';");
    expect(index).toContain("export * as Entities from './entities';");
  });
});

// ---------------------------------------------------------------------------
// Endpoints — runtime
// ---------------------------------------------------------------------------

describe('generateEndpointsRuntime — flat file', () => {
  const leaf = endpointLeaf(['user'], 'user');

  it('emits namespace import for user endpoint', () => {
    const out = generateEndpointsRuntime([leaf], '../src');
    expect(out).toContain("import * as user from '../src/endpoints/user';");
  });

  it('emits endpoints object with user key', () => {
    const out = generateEndpointsRuntime([leaf], '../src');
    expect(out).toContain('export const endpoints = {');
    expect(out).toContain('user: user');
  });

  it('emits Endpoints type alias', () => {
    const out = generateEndpointsRuntime([leaf], '../src');
    expect(out).toContain('export type Endpoints = typeof endpoints;');
  });
});

describe('generateEndpointsRuntime — nested endpoint', () => {
  const leaf = endpointLeaf(['admin', 'users'], 'admin/users');

  it('emits double-underscore alias for nested endpoint', () => {
    const out = generateEndpointsRuntime([leaf], '../src');
    expect(out).toContain("import * as admin__users from '../src/endpoints/admin/users';");
  });

  it('emits nested object structure', () => {
    const out = generateEndpointsRuntime([leaf], '../src');
    expect(out).toContain('admin: {');
    expect(out).toContain('users: admin__users');
  });
});

describe('generateEndpointsRuntime — empty endpoints', () => {
  it('emits empty endpoints object (no crash)', () => {
    const out = generateEndpointsRuntime([], '../src');
    expect(out).toContain('export const endpoints = {} as const;');
    expect(out).toContain('export type Endpoints = typeof endpoints;');
  });
});

// ---------------------------------------------------------------------------
// Endpoints — types
// ---------------------------------------------------------------------------

describe('generateEndpointsTypes', () => {
  it('imports InferApi from @capsuletech/web-query', () => {
    const out = generateEndpointsTypes();
    expect(out).toContain("import type { InferApi } from '@capsuletech/web-query';");
  });

  it('imports Endpoints from registry/endpoints', () => {
    const out = generateEndpointsTypes();
    expect(out).toContain("import type { Endpoints } from '../registry/endpoints';");
  });

  it('declares CapsuleApi global interface extending InferApi', () => {
    const out = generateEndpointsTypes();
    expect(out).toContain('interface CapsuleApi extends InferApi<Endpoints> {}');
  });

  it('has export {} for module augmentation', () => {
    const out = generateEndpointsTypes();
    expect(out).toContain('export {};');
  });
});

// ---------------------------------------------------------------------------
// AppConfig — runtime
// ---------------------------------------------------------------------------

describe('generateAppConfigRuntime', () => {
  it('contains registerAliases call', () => {
    const out = generateAppConfigRuntime({});
    expect(out).toContain("import { registerAliases } from '@capsuletech/web-state';");
    expect(out).toContain('registerAliases(');
  });

  it('contains createApi and setApiClient guarded by api check', () => {
    const out = generateAppConfigRuntime({});
    expect(out).toContain("import { createApi, setApiClient } from '@capsuletech/web-query';");
    expect(out).toContain('if (appConfig.api) {');
    expect(out).toContain('setApiClient(createApi(appConfig.api, endpoints));');
  });

  it('contains type-only IAppConfig import', () => {
    const out = generateAppConfigRuntime({});
    expect(out).toContain("import { type IAppConfig } from '@capsuletech/web-core/app-config';");
  });

  it('uses static endpoints import (not dynamic)', () => {
    const out = generateAppConfigRuntime({});
    expect(out).toContain("import { endpoints } from './registry/endpoints';");
    expect(out).not.toContain("import('./registry/endpoints')");
  });

  it('serializes aliases JSON into registerAliases call', () => {
    const out = generateAppConfigRuntime({ '@input': ['login', 'input'] });
    expect(out).toContain('"@input"');
  });

  it('handles undefined aliases (defaults to empty object)', () => {
    const out = generateAppConfigRuntime(undefined);
    expect(out).toContain('registerAliases({});');
  });
});

// ---------------------------------------------------------------------------
// Bootstrap — generated content
// ---------------------------------------------------------------------------

describe('generateBootstrap — structure', () => {
  it('contains styles.css import', () => {
    const out = generateBootstrap();
    expect(out).toContain("import './styles.css';");
  });

  it('contains BaseProviders import', () => {
    const out = generateBootstrap();
    expect(out).toContain("import { BaseProviders } from '@capsuletech/web-core/providers';");
  });

  it('contains Bootstrap component export', () => {
    const out = generateBootstrap();
    expect(out).toContain('export const Bootstrap = () => {');
    expect(out).toContain('<BaseProviders');
    expect(out).toContain('routeTree={routeTree}');
    expect(out).toContain('basepath={import.meta.env.BASE_URL}');
  });

  it('starts with generated comment (not user-editable)', () => {
    const out = generateBootstrap();
    expect(out.startsWith('// generated by CapsuleRegistryPlugin')).toBe(true);
  });

  it('imports IAppConfig type and appConfigRaw from capsule.app', () => {
    const out = generateBootstrap();
    expect(out).toContain("import { type IAppConfig } from '@capsuletech/web-core/app-config';");
    expect(out).toContain("import appConfigRaw from '../capsule.app';");
  });

  it('casts appConfigRaw to IAppConfig', () => {
    const out = generateBootstrap();
    expect(out).toContain('const appConfig = appConfigRaw as IAppConfig;');
  });

  it('passes notFoundRedirect from appConfig.router to BaseProviders', () => {
    const out = generateBootstrap();
    expect(out).toContain('notFoundRedirect={appConfig.router?.notFoundRedirect}');
  });

  it('passes beforeLoad from appConfig.router to BaseProviders', () => {
    const out = generateBootstrap();
    expect(out).toContain('beforeLoad={appConfig.router?.beforeLoad}');
  });

  it('does NOT import wrappers side-effect (ADR-034: no globalThis assign)', () => {
    const out = generateBootstrap();
    expect(out).not.toContain("import './registry/wrappers'");
    expect(out).not.toContain('registry/wrappers');
  });

  it('does NOT contain Object.assign or globalThis (ADR-034)', () => {
    const out = generateBootstrap();
    expect(out).not.toContain('Object.assign');
    expect(out).not.toContain('globalThis');
  });
});

describe('generateBootstrap — import order matches LAYER_INIT_ORDER', () => {
  it('packages (globals) imported before app-config (subsystems)', () => {
    const out = generateBootstrap();
    const packagesIdx = out.indexOf("import './registry/packages'");
    const appConfigIdx = out.indexOf("import './app-config.gen'");
    expect(packagesIdx).toBeGreaterThanOrEqual(0);
    expect(appConfigIdx).toBeGreaterThanOrEqual(0);
    expect(packagesIdx).toBeLessThan(appConfigIdx);
  });

  it('app-config (subsystems) imported before routeTree (render)', () => {
    const out = generateBootstrap();
    const appConfigIdx = out.indexOf("import './app-config.gen'");
    const routeTreeIdx = out.indexOf("import { routeTree } from './routes/routeTree.gen'");
    expect(appConfigIdx).toBeGreaterThanOrEqual(0);
    expect(routeTreeIdx).toBeGreaterThanOrEqual(0);
    expect(appConfigIdx).toBeLessThan(routeTreeIdx);
  });

  it('packages uses bare side-effect import (no named binding)', () => {
    const out = generateBootstrap();
    expect(out).toMatch(/import '\.\/registry\/packages'/);
    expect(out).not.toMatch(/import \{[^}]*\} from '\.\/registry\/packages'/);
  });

  it('routeTree uses named import', () => {
    const out = generateBootstrap();
    expect(out).toContain("import { routeTree } from './routes/routeTree.gen';");
  });

  it('all LAYER_INIT_ORDER entries appear in the bootstrap output', () => {
    const out = generateBootstrap();
    for (const layer of LAYER_INIT_ORDER) {
      expect(out).toContain(layer.importPath);
    }
  });

  it('bootstrap import order is exactly the same as LAYER_INIT_ORDER', () => {
    const out = generateBootstrap();
    const positions = LAYER_INIT_ORDER.map((layer) => out.indexOf(layer.importPath));
    // Positions must be strictly increasing.
    for (let i = 1; i < positions.length; i++) {
      expect(positions[i]).toBeGreaterThan(positions[i - 1]);
    }
  });
});

// ---------------------------------------------------------------------------
// LAYER_INIT_ORDER contract
// ---------------------------------------------------------------------------

describe('LAYER_INIT_ORDER contract', () => {
  it("'globals' phase comes before 'subsystems' which comes before 'render'", () => {
    const phases = LAYER_INIT_ORDER.map((e) => e.phase);
    const firstSubsystems = phases.indexOf('subsystems');
    const firstRender = phases.indexOf('render');
    const lastGlobals = phases.lastIndexOf('globals');

    expect(lastGlobals).toBeLessThan(firstSubsystems);
    expect(firstSubsystems).toBeLessThan(firstRender);
  });

  it("does NOT contain a 'wrappers' entry (ADR-034: barrel replaces wrappers.ts)", () => {
    const entry = LAYER_INIT_ORDER.find((e) => e.name === 'wrappers');
    expect(entry).toBeUndefined();
  });

  it("'packages' entry exists and is phase 'globals'", () => {
    const entry = LAYER_INIT_ORDER.find((e) => e.name === 'packages');
    expect(entry).toBeDefined();
    expect(entry!.phase).toBe('globals');
  });

  it("'routes' entry is phase 'render'", () => {
    const entry = LAYER_INIT_ORDER.find((e) => e.name === 'routes');
    expect(entry).toBeDefined();
    expect(entry!.phase).toBe('render');
  });

  it('all entries have unique names', () => {
    const names = LAYER_INIT_ORDER.map((e) => e.name);
    const unique = new Set(names);
    expect(unique.size).toBe(names.length);
  });

  it('all entries have non-empty importPath', () => {
    for (const entry of LAYER_INIT_ORDER) {
      expect(entry.importPath.length).toBeGreaterThan(0);
    }
  });
});

// ---------------------------------------------------------------------------
// CapsuleRegistryPlugin transform hooks
// ---------------------------------------------------------------------------

const WATCH_DIR = resolve('/project/apps/myapp/src');
const CAPSULE_ROOT = resolve('/project/apps/myapp/.capsule');
const APP_CONFIG_PATH = resolve('/project/apps/myapp/capsule.app.ts');
const ENDPOINTS_DIR_ABS = resolve(WATCH_DIR, 'endpoints');

function makePlugin() {
  return CapsuleRegistryPlugin({
    capsuleRoot: CAPSULE_ROOT,
    watchDir: WATCH_DIR,
    appConfigPath: APP_CONFIG_PATH,
  }) as Plugin & {
    transform: (code: string, id: string) => { code: string } | null;
  };
}

function callTransform(plugin: ReturnType<typeof makePlugin>, code: string, id: string) {
  return plugin.transform(code, id);
}

describe('CapsuleRegistryPlugin.transform — defineEndpoint injection', () => {
  it('injects defineEndpoint import into endpoint files', () => {
    const plugin = makePlugin();
    const id = join(ENDPOINTS_DIR_ABS, 'auth.ts');
    const code = `export const login = defineEndpoint((z) => ({ method: 'POST', path: '/login' }));`;
    const result = callTransform(plugin, code, id);

    expect(result).not.toBeNull();
    expect(result!.code).toContain("import { defineEndpoint } from '@capsuletech/web-query'");
    expect(result!.code).toContain('export const login = defineEndpoint');
  });

  it('does NOT inject if defineEndpoint already explicitly imported (idempotent)', () => {
    const plugin = makePlugin();
    const id = join(ENDPOINTS_DIR_ABS, 'auth.ts');
    const code = [
      "import { defineEndpoint } from '@capsuletech/web-query';",
      `export const login = defineEndpoint((z) => ({ method: 'POST', path: '/login' }));`,
    ].join('\n');
    const result = callTransform(plugin, code, id);
    expect(result).toBeNull();
  });

  it('does NOT touch files outside src/endpoints/', () => {
    const plugin = makePlugin();
    const id = resolve(WATCH_DIR, 'features', 'auth.ts');
    const code = `export const useAuth = () => {};`;
    const result = callTransform(plugin, code, id);
    expect(result).toBeNull();
  });

  it('does NOT touch non-ts files inside endpoints/', () => {
    const plugin = makePlugin();
    const id = join(ENDPOINTS_DIR_ABS, 'README.md');
    const code = '# Auth endpoints';
    const result = callTransform(plugin, code, id);
    expect(result).toBeNull();
  });

  it('injection is placed BEFORE original code (no TDZ)', () => {
    const plugin = makePlugin();
    const id = join(ENDPOINTS_DIR_ABS, 'user.ts');
    const code = `export const getUser = defineEndpoint((z) => ({ method: 'GET', path: '/user' }));`;
    const result = callTransform(plugin, code, id);

    expect(result).not.toBeNull();
    const importIdx = result!.code.indexOf('import { defineEndpoint }');
    const codeIdx = result!.code.indexOf('export const getUser');
    expect(importIdx).toBeLessThan(codeIdx);
  });

  it('strips Vite query suffix from id before path matching', () => {
    const plugin = makePlugin();
    const id = join(ENDPOINTS_DIR_ABS, 'auth.ts') + '?t=12345';
    const code = `export const login = defineEndpoint((z) => ({ method: 'POST', path: '/login' }));`;
    const result = callTransform(plugin, code, id);
    expect(result).not.toBeNull();
    expect(result!.code).toContain('import { defineEndpoint }');
  });

  it('works for nested endpoint files', () => {
    const plugin = makePlugin();
    const id = join(ENDPOINTS_DIR_ABS, 'admin', 'users.ts');
    const code = `export const listUsers = defineEndpoint((z) => ({ method: 'GET', path: '/admin/users' }));`;
    const result = callTransform(plugin, code, id);
    expect(result).not.toBeNull();
    expect(result!.code).toContain('import { defineEndpoint }');
  });
});

describe('CapsuleRegistryPlugin.transform — defineAppConfig identity-unwrap', () => {
  const SOURCE = `export default defineAppConfig({ meta: { tags: ['a'] } });\n`;

  it('replaces defineAppConfig call-site with identity-unwrap in capsule.app.ts', () => {
    const plugin = makePlugin();
    const result = callTransform(plugin, SOURCE, APP_CONFIG_PATH);
    expect(result).not.toBeNull();
    expect(result!.code).not.toContain('defineAppConfig(');
    expect(result!.code).toContain('((__x__)=>__x__)(');
  });

  it('matches Windows-backslash configPath against POSIX id', () => {
    const winPath = 'D:\\repo\\apps\\myapp\\capsule.app.ts';
    const viteId = 'D:/repo/apps/myapp/capsule.app.ts';
    const plugin = CapsuleRegistryPlugin({
      capsuleRoot: CAPSULE_ROOT,
      watchDir: WATCH_DIR,
      appConfigPath: winPath,
    }) as Plugin & { transform: (code: string, id: string) => { code: string } | null };
    const result = plugin.transform(SOURCE, viteId);
    expect(result).not.toBeNull();
    expect(result!.code).toContain('((__x__)=>__x__)');
  });

  it('matches when Vite appends ?import suffix to id', () => {
    const plugin = makePlugin();
    const result = callTransform(plugin, SOURCE, APP_CONFIG_PATH + '?import');
    expect(result).not.toBeNull();
    expect(result!.code).toContain('((__x__)=>__x__)');
  });

  it('matches when Vite appends ?t=<ts> HMR suffix to id', () => {
    const plugin = makePlugin();
    const result = callTransform(plugin, SOURCE, APP_CONFIG_PATH + '?t=1736012345678');
    expect(result).not.toBeNull();
    expect(result!.code).toContain('((__x__)=>__x__)');
  });

  it('does NOT transform unrelated files', () => {
    const plugin = makePlugin();
    const result = callTransform(plugin, SOURCE, resolve(WATCH_DIR, 'main.tsx'));
    expect(result).toBeNull();
  });

  it('returns null if no defineAppConfig present (safe early exit)', () => {
    const plugin = makePlugin();
    const result = callTransform(plugin, `export default { foo: 1 };\n`, APP_CONFIG_PATH);
    expect(result).toBeNull();
  });

  it('preserves explicit import binding, replaces only call-site', () => {
    const plugin = makePlugin();
    const code = [
      `import { defineAppConfig } from '@capsuletech/web-core/app-config';`,
      `export default defineAppConfig({ meta: { tags: ['click'] }, aliases: {} });`,
      '',
    ].join('\n');
    const result = callTransform(plugin, code, APP_CONFIG_PATH);
    expect(result).not.toBeNull();
    expect(result!.code).toContain(
      `import { defineAppConfig } from '@capsuletech/web-core/app-config'`,
    );
    expect(result!.code).toContain('((__x__)=>__x__)({ meta:');
  });
});

// ---------------------------------------------------------------------------
// Packages — runtime (generatePackagesRuntime)
// ---------------------------------------------------------------------------

const pkgEntry = (
  pkg: string,
  globalName: string,
  controllerKeys?: string[],
): ResolvedPackageEntry => ({
  pkg,
  globalName,
  controllerKeys: controllerKeys && controllerKeys.length > 0 ? controllerKeys : undefined,
});

describe('generatePackagesRuntime — empty list', () => {
  it('emits valid empty module with bare Object.assign', () => {
    const out = generatePackagesRuntime([]);
    expect(out).toContain('Object.assign(globalThis, {});');
    expect(out).not.toContain('import ');
    expect(out).not.toContain('export const ');
  });

  it('starts with generated comment', () => {
    const out = generatePackagesRuntime([]);
    expect(out.startsWith('// generated by CapsuleRegistryPlugin')).toBe(true);
  });
});

describe('generatePackagesRuntime — single package', () => {
  const entries = [pkgEntry('@capsuletech/web-map', 'Maps')];

  it('imports <Name>_mod from the /capsule subpath', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain("import Maps_mod from '@capsuletech/web-map/capsule';");
  });

  it('exports const <Name> = <Name>_mod.components', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain('export const Maps = Maps_mod.components;');
  });

  it('Object.assign(globalThis) includes the global name', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain('Object.assign(globalThis, { Maps });');
  });

  it('Object.assign is at module top level (not indented)', () => {
    const out = generatePackagesRuntime(entries);
    const lines = out.split('\n');
    const assignLine = lines.find((l) => l.startsWith('Object.assign(globalThis,'));
    expect(assignLine).toBeDefined();
  });
});

describe('generatePackagesRuntime — two packages', () => {
  const entries = [
    pkgEntry('@capsuletech/web-map', 'Maps'),
    pkgEntry('@capsuletech/web-renderer', 'Render'),
  ];

  it('emits imports for both packages', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain("import Maps_mod from '@capsuletech/web-map/capsule';");
    expect(out).toContain("import Render_mod from '@capsuletech/web-renderer/capsule';");
  });

  it('emits exports for both packages', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain('export const Maps = Maps_mod.components;');
    expect(out).toContain('export const Render = Render_mod.components;');
  });

  it('Object.assign lists all global names', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain('Object.assign(globalThis, { Maps, Render });');
  });
});

// ---------------------------------------------------------------------------
// Packages — types (generatePackagesTypes)
// ---------------------------------------------------------------------------

describe('generatePackagesTypes — empty list', () => {
  it('emits minimal export {} (no declare global block)', () => {
    const out = generatePackagesTypes([]);
    expect(out).toContain('export {};');
    expect(out).not.toContain('declare global');
    expect(out).not.toContain('const ');
  });

  it('starts with generated comment', () => {
    const out = generatePackagesTypes([]);
    expect(out.startsWith('// generated by CapsuleRegistryPlugin')).toBe(true);
  });
});

describe('generatePackagesTypes — single package', () => {
  const entries = [pkgEntry('@capsuletech/web-map', 'Maps')];

  it('emits declare global block', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain('declare global {');
    expect(out).toContain('}');
  });

  it('declares const <Name> typed via typeof import /capsule .components', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain(
      "const Maps: typeof import('@capsuletech/web-map/capsule')['default']['components'];",
    );
  });

  it('contains export {} for module augmentation', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain('export {};');
  });

  it('const declaration is inside declare global block', () => {
    const out = generatePackagesTypes(entries);
    const globalStart = out.indexOf('declare global {');
    const globalEnd = out.lastIndexOf('}');
    const constIdx = out.indexOf('const Maps:');
    expect(constIdx).toBeGreaterThan(globalStart);
    expect(constIdx).toBeLessThan(globalEnd);
  });
});

describe('generatePackagesTypes — two packages', () => {
  const entries = [
    pkgEntry('@capsuletech/web-map', 'Maps'),
    pkgEntry('@capsuletech/web-renderer', 'Render'),
  ];

  it('declares const for each package', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain(
      "const Maps: typeof import('@capsuletech/web-map/capsule')['default']['components'];",
    );
    expect(out).toContain(
      "const Render: typeof import('@capsuletech/web-renderer/capsule')['default']['components'];",
    );
  });

  it('both const declarations are inside declare global', () => {
    const out = generatePackagesTypes(entries);
    const globalStart = out.indexOf('declare global {');
    const globalEnd = out.lastIndexOf('}');
    const mapsIdx = out.indexOf('const Maps:');
    const renderIdx = out.indexOf('const Render:');
    expect(mapsIdx).toBeGreaterThan(globalStart);
    expect(mapsIdx).toBeLessThan(globalEnd);
    expect(renderIdx).toBeGreaterThan(globalStart);
    expect(renderIdx).toBeLessThan(globalEnd);
  });
});

// ---------------------------------------------------------------------------
// LAYER_INIT_ORDER — packages entry contract
// ---------------------------------------------------------------------------

describe('LAYER_INIT_ORDER — packages entry', () => {
  it("'packages' entry exists", () => {
    const entry = LAYER_INIT_ORDER.find((e) => e.name === 'packages');
    expect(entry).toBeDefined();
  });

  it("'packages' entry is phase 'globals'", () => {
    const entry = LAYER_INIT_ORDER.find((e) => e.name === 'packages');
    expect(entry!.phase).toBe('globals');
  });

  it("'packages' entry importPath is './registry/packages'", () => {
    const entry = LAYER_INIT_ORDER.find((e) => e.name === 'packages');
    expect(entry!.importPath).toBe('./registry/packages');
  });

  it("'packages' (globals) appears before 'app-config' (subsystems)", () => {
    const packagesIdx = LAYER_INIT_ORDER.findIndex((e) => e.name === 'packages');
    const appConfigIdx = LAYER_INIT_ORDER.findIndex((e) => e.name === 'app-config');
    expect(packagesIdx).toBeGreaterThanOrEqual(0);
    expect(appConfigIdx).toBeGreaterThanOrEqual(0);
    expect(packagesIdx).toBeLessThan(appConfigIdx);
  });

  it('bootstrap contains packages side-effect import', () => {
    const out = generateBootstrap();
    expect(out).toContain("import './registry/packages';");
  });

  it('packages side-effect import appears before app-config in bootstrap', () => {
    const out = generateBootstrap();
    const packagesIdx = out.indexOf("import './registry/packages'");
    const appConfigIdx = out.indexOf("import './app-config.gen'");
    expect(packagesIdx).toBeLessThan(appConfigIdx);
  });
});

// ---------------------------------------------------------------------------
// Packages — runtime with controllerKeys (Controllers namespace augmentation)
// ---------------------------------------------------------------------------

describe('generatePackagesRuntime — package with controllers', () => {
  const entries = [pkgEntry('@capsuletech/web-dnd', 'Dnd', ['Editor'])];

  it('still emits import, export const, and Object.assign for components', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain("import Dnd_mod from '@capsuletech/web-dnd/capsule';");
    expect(out).toContain('export const Dnd = Dnd_mod.components;');
    expect(out).toContain('Object.assign(globalThis, { Dnd });');
  });

  it('augments Controllers via (globalThis.Controllers ??= {})[key] = ... (not overwrite)', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain(
      '(globalThis.Controllers ??= {})["Editor"] = Dnd_mod.controllers["Editor"];',
    );
    expect(out).not.toContain('globalThis.Controllers =');
  });

  it('Controllers augmentation appears BEFORE Object.assign (synchronous on eval)', () => {
    const out = generatePackagesRuntime(entries);
    const augmentIdx = out.indexOf('(globalThis.Controllers ??= {})');
    const assignIdx = out.indexOf('Object.assign(globalThis,');
    expect(augmentIdx).toBeGreaterThanOrEqual(0);
    expect(assignIdx).toBeGreaterThanOrEqual(0);
    expect(augmentIdx).toBeLessThan(assignIdx);
  });

  it('does NOT use Object.assign for Controllers (no risk of overwriting app-controllers)', () => {
    const out = generatePackagesRuntime(entries);
    const assignLine = out.split('\n').find((l) => l.startsWith('Object.assign(globalThis,'));
    expect(assignLine).toBeDefined();
    expect(assignLine).not.toContain('Controllers');
  });
});

describe('generatePackagesRuntime — package with multiple controllerKeys', () => {
  const entries = [pkgEntry('@capsuletech/web-dnd', 'Dnd', ['Editor', 'Canvas'])];

  it('emits augmentation for each controller key', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain(
      '(globalThis.Controllers ??= {})["Editor"] = Dnd_mod.controllers["Editor"];',
    );
    expect(out).toContain(
      '(globalThis.Controllers ??= {})["Canvas"] = Dnd_mod.controllers["Canvas"];',
    );
  });
});

describe('generatePackagesRuntime — two packages, one with controllers one without', () => {
  const entries = [
    pkgEntry('@capsuletech/web-map', 'Maps'),
    pkgEntry('@capsuletech/web-dnd', 'Dnd', ['Editor']),
  ];

  it('only augments Controllers for the package that has controllers', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain('(globalThis.Controllers ??= {})["Editor"] = Dnd_mod.controllers');
    expect(out).not.toContain('Maps_mod.controllers');
  });

  it('Object.assign includes both global names', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain('Object.assign(globalThis, { Maps, Dnd });');
  });
});

describe('generatePackagesRuntime — package without controllers (no regression)', () => {
  const entries = [pkgEntry('@capsuletech/web-map', 'Maps')];

  it('does NOT emit any Controllers augmentation', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).not.toContain('Controllers');
    expect(out).not.toContain('controllers');
  });

  it('structure is identical to pre-controllers behavior', () => {
    const out = generatePackagesRuntime(entries);
    expect(out).toContain("import Maps_mod from '@capsuletech/web-map/capsule';");
    expect(out).toContain('export const Maps = Maps_mod.components;');
    expect(out).toContain('Object.assign(globalThis, { Maps });');
  });
});

describe('generatePackagesRuntime — app-controllers are not clobbered (augment invariant)', () => {
  it('packages.ts uses (??=) augmentation so existing keys are preserved', () => {
    const entries = [pkgEntry('@capsuletech/web-dnd', 'Dnd', ['Editor'])];
    const out = generatePackagesRuntime(entries);
    expect(out).toContain('??=');
    expect(out).not.toMatch(/globalThis\.Controllers\s*=\s*\{/);
    expect(out).not.toMatch(/Object\.assign\(globalThis,\s*\{[^}]*Controllers/);
  });
});

// ---------------------------------------------------------------------------
// Packages — types with controllerKeys (Controllers interface augmentation)
// ---------------------------------------------------------------------------

describe('generatePackagesTypes — package with controllers', () => {
  const entries = [pkgEntry('@capsuletech/web-dnd', 'Dnd', ['Editor'])];

  it('emits component const declaration', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain(
      "const Dnd: typeof import('@capsuletech/web-dnd/capsule')['default']['components'];",
    );
  });

  it('emits Controllers interface augmentation inside declare global', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain('interface Controllers {');
    expect(out).toContain(
      "Editor: typeof import('@capsuletech/web-dnd/capsule')['default']['controllers'][\"Editor\"];",
    );
  });

  it('Controllers interface is inside declare global block', () => {
    const out = generatePackagesTypes(entries);
    const globalStart = out.indexOf('declare global {');
    const globalEnd = out.lastIndexOf('}');
    const interfaceIdx = out.indexOf('interface Controllers {');
    expect(interfaceIdx).toBeGreaterThan(globalStart);
    expect(interfaceIdx).toBeLessThan(globalEnd);
  });

  it('contains export {} for module augmentation', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain('export {};');
  });
});

describe('generatePackagesTypes — package with multiple controllerKeys', () => {
  const entries = [pkgEntry('@capsuletech/web-dnd', 'Dnd', ['Editor', 'Canvas'])];

  it('emits a property for each controller key', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain(
      "Editor: typeof import('@capsuletech/web-dnd/capsule')['default']['controllers'][\"Editor\"];",
    );
    expect(out).toContain(
      "Canvas: typeof import('@capsuletech/web-dnd/capsule')['default']['controllers'][\"Canvas\"];",
    );
  });
});

describe('generatePackagesTypes — two packages, one with controllers one without', () => {
  const entries = [
    pkgEntry('@capsuletech/web-map', 'Maps'),
    pkgEntry('@capsuletech/web-dnd', 'Dnd', ['Editor']),
  ];

  it('emits const for both component namespaces', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain(
      "const Maps: typeof import('@capsuletech/web-map/capsule')['default']['components'];",
    );
    expect(out).toContain(
      "const Dnd: typeof import('@capsuletech/web-dnd/capsule')['default']['components'];",
    );
  });

  it('emits Controllers interface only for Dnd (not Maps)', () => {
    const out = generatePackagesTypes(entries);
    expect(out).toContain('interface Controllers {');
    expect(out).toContain("'@capsuletech/web-dnd/capsule'");
    expect(out).not.toContain("'@capsuletech/web-map/capsule'['default']['controllers']");
  });

  it('exactly one interface Controllers block is emitted', () => {
    const out = generatePackagesTypes(entries);
    const count = (out.match(/interface Controllers \{/g) ?? []).length;
    expect(count).toBe(1);
  });
});

describe('generatePackagesTypes — package without controllers (no regression)', () => {
  const entries = [pkgEntry('@capsuletech/web-map', 'Maps')];

  it('does NOT emit Controllers interface augmentation', () => {
    const out = generatePackagesTypes(entries);
    expect(out).not.toContain('interface Controllers');
    expect(out).not.toContain('controllers');
  });
});

// ---------------------------------------------------------------------------
// parseManifestSource — static AST parsing (Ф0 фикс)
// ---------------------------------------------------------------------------

const MANIFEST_WITH_CONTROLLERS = `
import { defineCapsuleModule as s } from "@capsuletech/web-core/module";
var c = s({
  name: "Editor",
  components: { Overlay: i, Provider: e },
  controllers: { Editor: t }
});
export { c as default };
`;

const MANIFEST_WITHOUT_CONTROLLERS = `
import { defineCapsuleModule as s } from "@capsuletech/web-core/module";
var c = s({
  name: "Maps",
  components: { Map: m, Marker: k }
});
export { c as default };
`;

const MANIFEST_WITH_SOLID_IMPORTS = `
import { Portal as g, template as E } from "solid-js/web";
import { For as O } from "solid-js";
import { Renderer as R } from "@capsuletech/web-renderer";
import { defineCapsuleModule as s } from "@capsuletech/web-core/module";
var c = s({
  name: "Render",
  components: { View: R },
  controllers: { Editor: E }
});
export { c as default };
`;

const MANIFEST_NO_NAME = `
import { defineCapsuleModule as s } from "@capsuletech/web-core/module";
var c = s({ components: { Foo: f } });
export { c as default };
`;

const MANIFEST_REAL_STYLE = `
import { d as e, h as t, l as n } from "./chunks/EditorInspector.mjs";
import { defineCapsuleModule as s } from "@capsuletech/web-core/module";
var c = s({
  name: "Editor",
  components: {
    Overlay: e,
    Provider: n,
    Canvas: t
  },
  controllers: { Editor: t }
});
export { c as default };
`;

describe('parseManifestSource — static AST manifest (Ф0)', () => {
  it('parses name and controllerKeys from compiled capsule.mjs without executing it', () => {
    const result = parseManifestSource(MANIFEST_WITH_CONTROLLERS, 'capsule.mjs');
    expect(result).not.toBeNull();
    expect(result!.name).toBe('Editor');
    expect(result!.controllerKeys).toEqual(['Editor']);
  });

  it('returns controllerKeys=[] when controllers property absent', () => {
    const result = parseManifestSource(MANIFEST_WITHOUT_CONTROLLERS, 'capsule.mjs');
    expect(result).not.toBeNull();
    expect(result!.name).toBe('Maps');
    expect(result!.controllerKeys).toEqual([]);
  });

  it('does NOT throw when manifest contains solid-js/web / web-renderer imports', () => {
    let result: ReturnType<typeof parseManifestSource>;
    expect(() => {
      result = parseManifestSource(MANIFEST_WITH_SOLID_IMPORTS, 'capsule.mjs');
    }).not.toThrow();
    expect(result!).not.toBeNull();
    expect(result!.name).toBe('Render');
    expect(result!.controllerKeys).toEqual(['Editor']);
  });

  it('returns null when no name StringLiteral found', () => {
    const result = parseManifestSource(MANIFEST_NO_NAME, 'capsule.mjs');
    expect(result).toBeNull();
  });

  it('parses real-style manifest with nested components ObjectExpression', () => {
    const result = parseManifestSource(MANIFEST_REAL_STYLE, 'capsule.mjs');
    expect(result).not.toBeNull();
    expect(result!.name).toBe('Editor');
    expect(result!.controllerKeys).toEqual(['Editor']);
  });

  it('enables TypeScript plugin for .ts/.d.ts extension', () => {
    const tsSource = `
import { defineCapsuleModule } from "@capsuletech/web-core/module";
export default defineCapsuleModule({
  name: "MyPkg",
  components: {},
  controllers: { MyCtrl: {} as any },
});
`;
    const result = parseManifestSource(tsSource, 'capsule.ts');
    expect(result).not.toBeNull();
    expect(result!.name).toBe('MyPkg');
    expect(result!.controllerKeys).toEqual(['MyCtrl']);
  });

  it('handles shorthand controller keys { Editor } — Identifier key', () => {
    const source = `
var c = s({ name: "Editor", controllers: { Editor: f, Canvas: g } });
export { c as default };
`;
    const result = parseManifestSource(source, 'capsule.mjs');
    expect(result).not.toBeNull();
    expect(result!.controllerKeys).toEqual(['Editor', 'Canvas']);
  });

  it('handles StringLiteral controller keys { "Editor": f }', () => {
    const source = `
var c = s({ name: "Editor", controllers: { "Editor": f } });
export { c as default };
`;
    const result = parseManifestSource(source, 'capsule.mjs');
    expect(result).not.toBeNull();
    expect(result!.controllerKeys).toEqual(['Editor']);
  });

  it('ignores nested ObjectExpressions that lack a name property', () => {
    const source = `
var c = s({ name: "Editor", components: { sub: { key: 1 } }, controllers: { Editor: f } });
export { c as default };
`;
    const result = parseManifestSource(source, 'capsule.mjs');
    expect(result).not.toBeNull();
    expect(result!.name).toBe('Editor');
  });
});

// ---------------------------------------------------------------------------
// resolvePackageEntries — integration of FS I/O + parseManifestSource
// ---------------------------------------------------------------------------

const MOCK_CAPSULE_MJS_WITH_CONTROLLERS = `
import { defineCapsuleModule as s } from "@capsuletech/web-core/module";
var c = s({
  name: "Editor",
  components: { Overlay: o, Provider: p },
  controllers: { Editor: e }
});
export { c as default };
`;

const MOCK_CAPSULE_MJS_NO_CONTROLLERS = `
import { defineCapsuleModule as s } from "@capsuletech/web-core/module";
var c = s({
  name: "Maps",
  components: { Map: m }
});
export { c as default };
`;

describe('resolvePackageEntries — empty raw list', () => {
  it('returns [] for undefined', () => {
    expect(resolvePackageEntries(undefined, '/app')).toEqual([]);
  });

  it('returns [] for empty array', () => {
    expect(resolvePackageEntries([], '/app')).toEqual([]);
  });
});

describe('resolvePackageEntries — single string entry with controllers (mocked FS)', () => {
  it('parseManifestSource produces correct ResolvedPackageEntry shape for ui-creator manifest', () => {
    const parsed = parseManifestSource(MOCK_CAPSULE_MJS_WITH_CONTROLLERS, 'capsule.mjs');
    expect(parsed).not.toBeNull();
    const simulatedEntry: ResolvedPackageEntry = {
      pkg: '@capsuletech/web-ui-creator',
      globalName: parsed!.name,
      controllerKeys: parsed!.controllerKeys.length > 0 ? parsed!.controllerKeys : undefined,
    };
    expect(simulatedEntry.globalName).toBe('Editor');
    expect(simulatedEntry.controllerKeys).toEqual(['Editor']);
    expect(simulatedEntry.pkg).toBe('@capsuletech/web-ui-creator');
  });

  it('generatePackagesRuntime from resolved ui-creator entry matches real packages.ts format', () => {
    const parsed = parseManifestSource(MOCK_CAPSULE_MJS_WITH_CONTROLLERS, 'capsule.mjs');
    const entries: ResolvedPackageEntry[] = [
      {
        pkg: '@capsuletech/web-ui-creator',
        globalName: parsed!.name,
        controllerKeys: parsed!.controllerKeys.length > 0 ? parsed!.controllerKeys : undefined,
      },
    ];
    const runtime = generatePackagesRuntime(entries);
    expect(runtime).toContain("import Editor_mod from '@capsuletech/web-ui-creator/capsule';");
    expect(runtime).toContain('export const Editor = Editor_mod.components;');
    expect(runtime).toContain(
      '(globalThis.Controllers ??= {})["Editor"] = Editor_mod.controllers["Editor"];',
    );
    expect(runtime).toContain('Object.assign(globalThis, { Editor });');
  });

  it('generatePackagesTypes from resolved ui-creator entry matches real packages.d.ts format', () => {
    const parsed = parseManifestSource(MOCK_CAPSULE_MJS_WITH_CONTROLLERS, 'capsule.mjs');
    const entries: ResolvedPackageEntry[] = [
      {
        pkg: '@capsuletech/web-ui-creator',
        globalName: parsed!.name,
        controllerKeys: parsed!.controllerKeys.length > 0 ? parsed!.controllerKeys : undefined,
      },
    ];
    const types = generatePackagesTypes(entries);
    expect(types).toContain('declare global {');
    expect(types).toContain(
      "const Editor: typeof import('@capsuletech/web-ui-creator/capsule')['default']['components'];",
    );
    expect(types).toContain('interface Controllers {');
    expect(types).toContain(
      "Editor: typeof import('@capsuletech/web-ui-creator/capsule')['default']['controllers'][\"Editor\"];",
    );
    expect(types).toContain('export {};');
  });
});

describe('resolvePackageEntries — package without controllers (web-map style)', () => {
  it('generatePackagesRuntime for map-style (no controllers) has no Controllers augmentation', () => {
    const parsed = parseManifestSource(MOCK_CAPSULE_MJS_NO_CONTROLLERS, 'capsule.mjs');
    const entries: ResolvedPackageEntry[] = [
      {
        pkg: '@capsuletech/web-map',
        globalName: parsed!.name,
        controllerKeys: undefined,
      },
    ];
    const runtime = generatePackagesRuntime(entries);
    expect(runtime).toContain("import Maps_mod from '@capsuletech/web-map/capsule';");
    expect(runtime).toContain('export const Maps = Maps_mod.components;');
    expect(runtime).not.toContain('Controllers');
    expect(runtime).toContain('Object.assign(globalThis, { Maps });');
  });

  it('generatePackagesTypes for map-style has no Controllers interface', () => {
    const parsed = parseManifestSource(MOCK_CAPSULE_MJS_NO_CONTROLLERS, 'capsule.mjs');
    const entries: ResolvedPackageEntry[] = [
      {
        pkg: '@capsuletech/web-map',
        globalName: parsed!.name,
        controllerKeys: undefined,
      },
    ];
    const types = generatePackagesTypes(entries);
    expect(types).not.toContain('interface Controllers');
    expect(types).toContain(
      "const Maps: typeof import('@capsuletech/web-map/capsule')['default']['components'];",
    );
  });
});

describe('resolvePackageEntries — { use, as } override form', () => {
  it('parseManifestSource + as-override yields overridden globalName', () => {
    const globalName = 'MyMap'; // entry.as override
    const entries: ResolvedPackageEntry[] = [
      { pkg: '@capsuletech/web-map', globalName, controllerKeys: undefined },
    ];
    const runtime = generatePackagesRuntime(entries);
    expect(runtime).toContain("import MyMap_mod from '@capsuletech/web-map/capsule';");
    expect(runtime).toContain('export const MyMap = MyMap_mod.components;');
    expect(runtime).toContain('Object.assign(globalThis, { MyMap });');
  });
});

// ---------------------------------------------------------------------------
// CapsuleRegistryPlugin.config — alias registration (ADR-034 dev-server fix)
// ---------------------------------------------------------------------------

describe("CapsuleRegistryPlugin.config — '@capsule/registry' alias", () => {
  it('config() hook returns resolve.alias with @capsule/registry pointing to registry/index.ts', () => {
    const plugin = makePlugin() as Plugin & { config: () => { resolve: { alias: Record<string, string> } } };
    const result = plugin.config();
    expect(result).toBeDefined();
    expect(result.resolve).toBeDefined();
    expect(result.resolve.alias).toBeDefined();
    const alias = result.resolve.alias;
    expect(alias['@capsule/registry']).toBe(resolve(CAPSULE_ROOT, 'registry', 'index.ts'));
  });

  it('alias path ends with .capsule/registry/index.ts', () => {
    const plugin = makePlugin() as Plugin & { config: () => { resolve: { alias: Record<string, string> } } };
    const result = plugin.config();
    const aliasPath = result.resolve.alias['@capsule/registry'];
    expect(aliasPath.replace(/\\/g, '/')).toContain('.capsule/registry/index.ts');
  });

  it('different capsuleRoot produces different alias path', () => {
    const plugin1 = CapsuleRegistryPlugin({
      capsuleRoot: resolve('/project/apps/app1/.capsule'),
      watchDir: WATCH_DIR,
      appConfigPath: APP_CONFIG_PATH,
    }) as Plugin & { config: () => { resolve: { alias: Record<string, string> } } };
    const plugin2 = CapsuleRegistryPlugin({
      capsuleRoot: resolve('/project/apps/app2/.capsule'),
      watchDir: WATCH_DIR,
      appConfigPath: APP_CONFIG_PATH,
    }) as Plugin & { config: () => { resolve: { alias: Record<string, string> } } };

    const path1 = plugin1.config().resolve.alias['@capsule/registry'];
    const path2 = plugin2.config().resolve.alias['@capsule/registry'];
    expect(path1).not.toBe(path2);
    expect(path1.replace(/\\/g, '/')).toContain('app1');
    expect(path2.replace(/\\/g, '/')).toContain('app2');
  });

  it('plugin does NOT have a configResolved hook (alias must not be double-registered)', () => {
    const plugin = makePlugin() as Plugin;
    expect(plugin).not.toHaveProperty('configResolved');
  });
});
