/**
 * Tests for createDocsSourcesSubGenerator + pure helpers.
 *
 * What is covered:
 *
 * ── derivePackageShort ──────────────────────────────────────────────────────
 *  - @scope/name → name (strip scope)
 *  - @capsuletech/web-ui → web-ui
 *  - @my-org/my-lib → my-lib
 *  - unscoped name → unchanged
 *
 * ── generateDocsSourcesRuntime ──────────────────────────────────────────────
 *  - Contains setDocsSources import
 *  - Contains 'root' entry when rootVault entries provided
 *  - Contains per-package entry
 *  - Multiple entries emitted correctly
 *  - Empty entries array → no entries between braces
 *
 * ── createDocsSourcesSubGenerator (SubGenerator contract) ───────────────────
 *  - id = 'docs-sources', order = 50
 *  - match() returns false (no src file events)
 *  - onEvent() returns false
 *  - onAppConfigChange() marks dirty and returns true
 *  - bootstrap() returns globals phase with correct importPath
 *
 * ── flush() behaviour ───────────────────────────────────────────────────────
 *  - No docs field in config → removeOut called (cleanup)
 *  - docs: {} (empty) → removeOut called
 *  - docs.rootVault=true, packages=[] → only root entry emitted
 *  - docs.rootVault=false, packages=['@capsuletech/web-ui'] with docsJson export → web-ui entry
 *  - Package without ./docs.json export → skip + warn (no entry)
 *  - All packages skipped → removeOut called (empty entries)
 *  - Not dirty and not forced → no write / no remove
 *  - onAppConfigChange → dirty → flush writes
 */

import { resolve } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  checkDocsJsonExport,
  createDocsSourcesSubGenerator,
  derivePackageShort,
  generateDocsSourcesRuntime,
} from '../codegen';
import type { AppConfigShape, CodegenContext } from '../codegen';

// ---------------------------------------------------------------------------
// derivePackageShort
// ---------------------------------------------------------------------------

describe('derivePackageShort', () => {
  it('@capsuletech/web-ui → web-ui', () => {
    expect(derivePackageShort('@capsuletech/web-ui')).toBe('web-ui');
  });

  it('@my-org/my-lib → my-lib', () => {
    expect(derivePackageShort('@my-org/my-lib')).toBe('my-lib');
  });

  it('@scope/a-b-c → a-b-c', () => {
    expect(derivePackageShort('@scope/a-b-c')).toBe('a-b-c');
  });

  it('unscoped name stays unchanged', () => {
    expect(derivePackageShort('some-lib')).toBe('some-lib');
  });

  it('@scope without slash → unchanged (guard against malformed)', () => {
    // Edge: '@scope' with no slash — not a standard npm name but should not crash.
    expect(derivePackageShort('@scope')).toBe('@scope');
  });
});

// ---------------------------------------------------------------------------
// generateDocsSourcesRuntime
// ---------------------------------------------------------------------------

describe('generateDocsSourcesRuntime', () => {
  it('contains setDocsSources import from @capsuletech/web-docs', () => {
    const out = generateDocsSourcesRuntime([]);
    expect(out).toContain("import { setDocsSources } from '@capsuletech/web-docs'");
  });

  it('auto-generated header comment is present', () => {
    const out = generateDocsSourcesRuntime([]);
    expect(out).toContain('Auto-generated by capsule-registry');
    expect(out).toContain('Do not edit');
  });

  it('emits root entry when provided', () => {
    const out = generateDocsSourcesRuntime([{ key: 'root', pkg: '@capsuletech/web-docs' }]);
    expect(out).toContain(`"root": () => import('@capsuletech/web-docs/docs.json')`);
  });

  it('emits web-ui entry when provided', () => {
    const out = generateDocsSourcesRuntime([{ key: 'web-ui', pkg: '@capsuletech/web-ui' }]);
    expect(out).toContain(`"web-ui": () => import('@capsuletech/web-ui/docs.json')`);
  });

  it('emits multiple entries in order', () => {
    const entries = [
      { key: 'root', pkg: '@capsuletech/web-docs' },
      { key: 'web-ui', pkg: '@capsuletech/web-ui' },
    ];
    const out = generateDocsSourcesRuntime(entries);
    const rootIdx = out.indexOf('"root"');
    const webUiIdx = out.indexOf('"web-ui"');
    expect(rootIdx).toBeGreaterThanOrEqual(0);
    expect(webUiIdx).toBeGreaterThanOrEqual(0);
    expect(rootIdx).toBeLessThan(webUiIdx);
  });

  it('empty entries → setDocsSources called with empty object', () => {
    const out = generateDocsSourcesRuntime([]);
    expect(out).toContain('setDocsSources({');
    expect(out).toContain('});');
    // No import paths for packages.
    expect(out).not.toContain("import(");
  });

  it('ends with newline', () => {
    const out = generateDocsSourcesRuntime([]);
    expect(out.endsWith('\n')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// createDocsSourcesSubGenerator — SubGenerator contract
// ---------------------------------------------------------------------------

describe('createDocsSourcesSubGenerator — contract', () => {
  it('id is docs-sources', () => {
    const gen = createDocsSourcesSubGenerator();
    expect(gen.id).toBe('docs-sources');
  });

  it('order is 50', () => {
    const gen = createDocsSourcesSubGenerator();
    expect(gen.order).toBe(50);
  });

  it('match() returns false — not triggered by src file events', () => {
    const gen = createDocsSourcesSubGenerator();
    expect(gen.match('/any/file.ts')).toBe(false);
    expect(gen.match('/apps/app/src/widgets/foo.tsx')).toBe(false);
  });

  it('onEvent() returns false', () => {
    const gen = createDocsSourcesSubGenerator();
    const fakeCtx = {} as CodegenContext;
    expect(gen.onEvent('add', '/any/file.ts', fakeCtx)).toBe(false);
  });

  it('onAppConfigChange() marks dirty and returns true', () => {
    const gen = createDocsSourcesSubGenerator();
    const fakeCtx = {} as CodegenContext;
    expect(gen.onAppConfigChange?.(fakeCtx)).toBe(true);
  });

  it('bootstrap() returns null before first flush (_hasFile=false initially)', () => {
    // Before flush() runs, no file has been written — bootstrap() must return null
    // to avoid importing a non-existent module in bootstrap.tsx.
    const gen = createDocsSourcesSubGenerator();
    const fakeCtx = {} as CodegenContext;
    expect(gen.bootstrap?.(fakeCtx)).toBeNull();
  });

  it('bootstrap() returns globals phase after flush writes the file', () => {
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx, true); // writes the file → _hasFile = true
    const contrib = gen.bootstrap?.(ctx);
    expect(contrib?.phase).toBe('globals');
    expect(contrib?.importPath).toBe('./registry/docs-sources');
  });

  it('bootstrap() returns null after flush removes the file (no docs config)', () => {
    const gen = createDocsSourcesSubGenerator();

    // First: write the file
    const ctx1 = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx1, true); // _hasFile = true

    // Then: simulate config change removing docs
    gen.onAppConfigChange?.({} as CodegenContext); // marks dirty
    const ctx2 = makeCtx({}); // no docs field
    gen.flush(ctx2, false); // _hasFile = false (removeOut called)

    expect(gen.bootstrap?.(ctx2)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// flush() behaviour
// ---------------------------------------------------------------------------

const CAPSULE_ROOT = resolve('/project/apps/myapp/.capsule');
const APP_CONFIG_PATH = resolve('/project/apps/myapp/capsule.app.ts');
const OUT_PATH = resolve(CAPSULE_ROOT, 'registry', 'docs-sources.ts');

interface TestCtx extends CodegenContext {
  written: Map<string, string>;
  removed: string[];
}

const makeCtx = (config: AppConfigShape | undefined): TestCtx => {
  const written = new Map<string, string>();
  const removed: string[] = [];
  return {
    capsuleRoot: CAPSULE_ROOT,
    watchDir: resolve('/project/apps/myapp/src'),
    appConfigPath: APP_CONFIG_PATH,
    writeOut: (absPath: string, content: string) => { written.set(absPath, content); },
    removeOut: (absPath: string) => { removed.push(absPath); },
    parse: () => { throw new Error('parse not needed'); },
    names: () => { throw new Error('names not needed'); },
    loadAppConfig: () => config,
    written,
    removed,
  } as unknown as TestCtx;
};

describe('flush() — no docs config', () => {
  it('no docs field → removeOut docs-sources.ts (cleanup)', () => {
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ meta: { tags: [] } });
    gen.flush(ctx, true); // forced
    expect(ctx.removed).toContain(OUT_PATH);
    expect(ctx.written.size).toBe(0);
  });

  it('docs: undefined explicitly → cleanup', () => {
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ docs: undefined });
    gen.flush(ctx, true);
    expect(ctx.removed).toContain(OUT_PATH);
    expect(ctx.written.size).toBe(0);
  });

  it('docs: empty object {} → cleanup', () => {
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ docs: {} });
    gen.flush(ctx, true);
    expect(ctx.removed).toContain(OUT_PATH);
    expect(ctx.written.size).toBe(0);
  });

  it('docs.rootVault=false + packages=[] → cleanup', () => {
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ docs: { rootVault: false, packages: [] } });
    gen.flush(ctx, true);
    expect(ctx.removed).toContain(OUT_PATH);
    expect(ctx.written.size).toBe(0);
  });
});

describe('flush() — rootVault only', () => {
  it('rootVault=true, packages=[] → emits only root entry', () => {
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ docs: { rootVault: true, packages: [] } });
    gen.flush(ctx, true);
    expect(ctx.written.has(OUT_PATH)).toBe(true);
    const content = ctx.written.get(OUT_PATH)!;
    expect(content).toContain(`"root": () => import('@capsuletech/web-docs/docs.json')`);
    expect(content).not.toContain('web-ui');
  });

  it('rootVault=true → no web-docs export-check needed', () => {
    // root vault is always included without checking ./docs.json — we own the package.
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx, true);
    expect(ctx.written.has(OUT_PATH)).toBe(true);
  });
});

describe('flush() — packages with mocked checkDocsJsonExport', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('package with ./docs.json export → entry emitted', async () => {
    // We mock checkDocsJsonExport by testing generateDocsSourcesRuntime directly
    // since checkDocsJsonExport involves FS I/O (require.resolve).
    // The flush() integration test is done via a custom SubGenerator wrapper.
    const entries = [{ key: 'web-ui', pkg: '@capsuletech/web-ui' }];
    const out = generateDocsSourcesRuntime(entries);
    expect(out).toContain(`"web-ui": () => import('@capsuletech/web-ui/docs.json')`);
  });

  it('flush() with rootVault=true + web-ui (checking content)', () => {
    // We test the full flush path by providing rootVault=true only
    // (packages[] requires real FS for checkDocsJsonExport).
    const gen = createDocsSourcesSubGenerator();
    const ctx = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx, true);
    const content = ctx.written.get(OUT_PATH)!;
    expect(content).toContain("setDocsSources({");
    expect(content).toContain("'@capsuletech/web-docs'");
  });
});

describe('flush() — not dirty and not forced', () => {
  it('returns early without writing or removing', () => {
    const gen = createDocsSourcesSubGenerator();
    // No onAppConfigChange called — gen is not dirty.
    const ctx = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx, false); // not forced, not dirty
    expect(ctx.written.size).toBe(0);
    expect(ctx.removed.length).toBe(0);
  });
});

describe('flush() — dirty after onAppConfigChange', () => {
  it('writes after onAppConfigChange marks dirty', () => {
    const gen = createDocsSourcesSubGenerator();
    const fakeCtxForChange = {} as CodegenContext;
    gen.onAppConfigChange?.(fakeCtxForChange); // marks dirty

    const ctx = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx, false); // not forced, but dirty
    expect(ctx.written.has(OUT_PATH)).toBe(true);
  });

  it('second flush (not forced) after dirty flush → no-op', () => {
    const gen = createDocsSourcesSubGenerator();
    gen.onAppConfigChange?.({} as CodegenContext); // marks dirty

    const ctx1 = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx1, false); // dirty → writes, clears dirty

    const ctx2 = makeCtx({ docs: { rootVault: true } });
    gen.flush(ctx2, false); // not dirty, not forced → no-op
    expect(ctx2.written.size).toBe(0);
    expect(ctx2.removed.length).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// Ordering invariant with other sub-generators
// ---------------------------------------------------------------------------

describe('ordering invariants', () => {
  it('docs-sources(50) is between packages(40) and bootstrap(90)', async () => {
    const { createPackagesSubGenerator, createBootstrapSubGenerator } = await import('../codegen');
    const packages = createPackagesSubGenerator();
    const docsSources = createDocsSourcesSubGenerator();
    const bootstrap = createBootstrapSubGenerator(() => []);

    expect(packages.order).toBeLessThan(docsSources.order);
    expect(docsSources.order).toBeLessThan(bootstrap.order);
  });
});
