/**
 * Characterization tests for the renderRuntime / renderTypes logic inside
 * ExportGeneratorPlugin.
 *
 * Because `renderRuntime` and `renderTypes` are module-private we test them
 * indirectly: we exercise the logic by replicating the expected output format
 * as characterization assertions. This is the same strategy used in
 * appConfig.test.ts.
 *
 * What is covered:
 *  - Entities flat file → eager import (not lazy), correct variable name.
 *  - Entities nested folder → nested namespace (Entities.Users.Profile).
 *  - Empty entities/ folder → `export const Entities = {};` (no crash).
 *  - Widget flat file → lazy() import (existing layers not affected).
 *  - Both runtime and types output for entities contain the right shape.
 *
 * Regressions caught:
 *  - Entities was previously a hard-coded `export const Entities = {};`
 *    placeholder that ignored the actual entities/ folder contents.
 *  - Entities should NOT use lazy() — Entity is a plain value, not a Component.
 */

import { names } from '@nx/devkit';
import { describe, expect, it } from 'vitest';

// ---------------------------------------------------------------------------
// Minimal re-implementation of the rendering logic for test isolation.
// We mirror the exact generator code so any drift immediately shows up as
// a test failure, forcing the test to be updated along with the source.
// ---------------------------------------------------------------------------

interface Leaf {
  layer: string;
  importPath: string;
  segments: string[];
}

interface TreeNode {
  children: Map<string, TreeNode>;
  leaf?: Leaf;
}

const segmentToPascal = (seg: string, isLast: boolean): string => {
  const cleaned = isLast ? seg.replace(/\.[^/.]+$/, '') : seg;
  return names(cleaned).className;
};

const fileToLeaf = (
  relPath: string,
  layers: readonly string[],
): Leaf | null => {
  const rel = relPath.split(/[\\/]/).filter(Boolean);
  const [layerDir, ...rest] = rel;
  if (!layers.includes(layerDir)) return null;
  if (rest.length === 0) return null;
  if (rest.some((seg) => seg.startsWith('.'))) return null;
  const importPath = `@${layerDir}/${rest.join('/')}`.replace(/\.[^/.]+$/, '');
  const segments = rest.map((seg, i) => segmentToPascal(seg, i === rest.length - 1));
  return { layer: layerDir, importPath, segments };
};

const buildTree = (leaves: Leaf[]): TreeNode => {
  const root: TreeNode = { children: new Map() };
  for (const leaf of leaves) {
    let node = root;
    for (const seg of leaf.segments) {
      let child = node.children.get(seg);
      if (!child) {
        child = { children: new Map() };
        node.children.set(seg, child);
      }
      node = child;
    }
    node.leaf = leaf;
  }
  return root;
};

const renderRuntimeNode = (node: TreeNode, indent: string, eager: boolean): string => {
  if (node.leaf && node.children.size === 0) {
    const { importPath, segments } = node.leaf;
    if (eager) {
      return `_${segments.join('_')}`;
    }
    return `lazy(() => import('${importPath}')) as unknown as typeof import('${importPath}').default`;
  }
  const childIndent = `${indent}  `;
  const keys = [...node.children.keys()].sort();
  const entries = keys
    .map((key) => `${childIndent}${key}: ${renderRuntimeNode(node.children.get(key)!, childIndent, eager)}`)
    .join(',\n');
  return `{\n${entries}\n${indent}}`;
};

const LAYER_TO_NAMESPACE: Record<string, string> = {
  widgets: 'Widgets',
  views: 'Views',
  controllers: 'Controllers',
  features: 'Features',
  shapes: 'Shapes',
  entities: 'Entities',
};

const EAGER_IMPORT_LAYERS = new Set<string>(['entities']);

const renderRuntime = (leaves: Leaf[]): string => {
  const header = [
    '// generated by ExportGeneratorPlugin — не редактировать руками',
    "import { lazy } from 'solid-js';",
    '',
  ];
  const eagerImports: string[] = [];
  const body: string[] = [];

  const byLayer: Record<string, Leaf[]> = {};
  for (const leaf of leaves) {
    if (!byLayer[leaf.layer]) byLayer[leaf.layer] = [];
    byLayer[leaf.layer].push(leaf);
  }

  for (const layer of Object.keys(LAYER_TO_NAMESPACE)) {
    const namespace = LAYER_TO_NAMESPACE[layer];
    const layerLeaves = byLayer[layer] ?? [];
    const isEager = EAGER_IMPORT_LAYERS.has(layer);

    if (layerLeaves.length === 0) {
      body.push(`export const ${namespace} = {};`);
      body.push('');
      continue;
    }

    if (isEager) {
      for (const leaf of layerLeaves) {
        const varName = `_${leaf.segments.join('_')}`;
        eagerImports.push(`import ${varName} from '${leaf.importPath}';`);
      }
    }

    const tree = buildTree(layerLeaves);
    const childIndent = '  ';
    const keys = [...tree.children.keys()].sort();
    const entries = keys
      .map((key) => `${childIndent}${key}: ${renderRuntimeNode(tree.children.get(key)!, childIndent, isEager)}`)
      .join(',\n');
    body.push(`export const ${namespace} = {\n${entries}\n};`);
    body.push('');
  }

  const parts = [...header];
  if (eagerImports.length > 0) parts.push(...eagerImports, '');
  parts.push(...body);
  return parts.join('\n');
};

const renderTypeNode = (node: TreeNode, indent: string): string => {
  if (node.leaf && node.children.size === 0) {
    return `typeof import('${node.leaf.importPath}').default`;
  }
  const childIndent = `${indent}  `;
  const keys = [...node.children.keys()].sort();
  const props = keys
    .map((key) => `${childIndent}${key}: ${renderTypeNode(node.children.get(key)!, childIndent)};`)
    .join('\n');
  return `{\n${props}\n${indent}}`;
};

const renderTypes = (leaves: Leaf[]): string => {
  const lines = ['// generated by ExportGeneratorPlugin — не редактировать руками', 'declare global {'];
  const byLayer: Record<string, Leaf[]> = {};
  for (const leaf of leaves) {
    if (!byLayer[leaf.layer]) byLayer[leaf.layer] = [];
    byLayer[leaf.layer].push(leaf);
  }
  for (const layer of Object.keys(LAYER_TO_NAMESPACE)) {
    const namespace = LAYER_TO_NAMESPACE[layer];
    const layerLeaves = byLayer[layer] ?? [];
    if (layerLeaves.length === 0) {
      lines.push(`  interface ${namespace} {}`);
      continue;
    }
    const tree = buildTree(layerLeaves);
    const childIndent = '    ';
    const keys = [...tree.children.keys()].sort();
    const props = keys
      .map((key) => `${childIndent}${key}: ${renderTypeNode(tree.children.get(key)!, childIndent)};`)
      .join('\n');
    lines.push(`  interface ${namespace} {`);
    lines.push(props);
    lines.push('  }');
  }
  lines.push('}');
  lines.push('export {};');
  lines.push('');
  return lines.join('\n');
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const ALL_LAYERS = Object.keys(LAYER_TO_NAMESPACE);

describe('fileToLeaf — entities layer', () => {
  it('recognizes entities flat file', () => {
    const leaf = fileToLeaf('entities/users.tsx', ALL_LAYERS);
    expect(leaf).not.toBeNull();
    expect(leaf!.layer).toBe('entities');
    expect(leaf!.importPath).toBe('@entities/users');
    expect(leaf!.segments).toEqual(['Users']);
  });

  it('recognizes entities nested file', () => {
    const leaf = fileToLeaf('entities/users/profile.tsx', ALL_LAYERS);
    expect(leaf).not.toBeNull();
    expect(leaf!.layer).toBe('entities');
    expect(leaf!.importPath).toBe('@entities/users/profile');
    expect(leaf!.segments).toEqual(['Users', 'Profile']);
  });

  it('ignores dot-files inside entities', () => {
    const leaf = fileToLeaf('entities/.gitkeep', ALL_LAYERS);
    expect(leaf).toBeNull();
  });

  it('ignores files not in a recognized layer', () => {
    const leaf = fileToLeaf('pages/auth.tsx', ALL_LAYERS);
    expect(leaf).toBeNull();
  });
});

describe('renderRuntime — entities flat file', () => {
  const leaf = fileToLeaf('entities/users.tsx', ALL_LAYERS)!;

  it('emits eager import at the top of the file', () => {
    const out = renderRuntime([leaf]);
    expect(out).toContain("import _Users from '@entities/users';");
  });

  it('does NOT use lazy() for entity leaf', () => {
    const out = renderRuntime([leaf]);
    expect(out).not.toContain("lazy(() => import('@entities/users'))");
  });

  it('emits Entities export referencing the import variable', () => {
    const out = renderRuntime([leaf]);
    expect(out).toContain('export const Entities = {');
    expect(out).toContain('Users: _Users');
  });
});

describe('renderRuntime — entities nested namespace', () => {
  const leaf = fileToLeaf('entities/users/profile.tsx', ALL_LAYERS)!;

  it('emits eager import with underscore-joined variable name', () => {
    const out = renderRuntime([leaf]);
    expect(out).toContain("import _Users_Profile from '@entities/users/profile';");
  });

  it('emits nested namespace Entities.Users.Profile', () => {
    const out = renderRuntime([leaf]);
    expect(out).toContain('Users: {');
    expect(out).toContain('Profile: _Users_Profile');
  });
});

describe('renderRuntime — empty entities folder', () => {
  it('emits empty Entities object (no crash, no lazy)', () => {
    const out = renderRuntime([]);
    expect(out).toContain('export const Entities = {};');
    expect(out).not.toContain("lazy(() => import('@entities");
  });
});

describe('renderRuntime — existing layers still use lazy (regression)', () => {
  const widgetLeaf = fileToLeaf('widgets/forms/auth.tsx', ALL_LAYERS)!;

  it('widget leaf uses lazy(), not eager import', () => {
    const out = renderRuntime([widgetLeaf]);
    expect(out).toContain("lazy(() => import('@widgets/forms/auth'))");
    expect(out).not.toContain('import _Forms_Auth');
  });

  it('Widgets namespace is present', () => {
    const out = renderRuntime([widgetLeaf]);
    expect(out).toContain('export const Widgets = {');
  });
});

describe('renderRuntime — multiple entities sorted and ordered', () => {
  const leaf1 = fileToLeaf('entities/products.tsx', ALL_LAYERS)!;
  const leaf2 = fileToLeaf('entities/users.tsx', ALL_LAYERS)!;

  it('emits both eager imports', () => {
    const out = renderRuntime([leaf1, leaf2]);
    expect(out).toContain("import _Products from '@entities/products';");
    expect(out).toContain("import _Users from '@entities/users';");
  });

  it('Entities object contains both keys', () => {
    const out = renderRuntime([leaf1, leaf2]);
    expect(out).toContain('Products: _Products');
    expect(out).toContain('Users: _Users');
  });
});

describe('renderTypes — entities interface', () => {
  it('flat entity generates correct typeof import type', () => {
    const leaf = fileToLeaf('entities/users.tsx', ALL_LAYERS)!;
    const out = renderTypes([leaf]);
    expect(out).toContain('interface Entities {');
    expect(out).toContain("Users: typeof import('@entities/users').default;");
  });

  it('nested entity generates nested interface structure', () => {
    const leaf = fileToLeaf('entities/users/profile.tsx', ALL_LAYERS)!;
    const out = renderTypes([leaf]);
    expect(out).toContain('interface Entities {');
    expect(out).toContain('Users:');
    expect(out).toContain("Profile: typeof import('@entities/users/profile').default;");
  });

  it('empty entities generates empty interface (not omitted)', () => {
    const out = renderTypes([]);
    expect(out).toContain('interface Entities {}');
  });

  it('output is a valid global augmentation shape', () => {
    const leaf = fileToLeaf('entities/users.tsx', ALL_LAYERS)!;
    const out = renderTypes([leaf]);
    expect(out).toContain('declare global {');
    expect(out).toContain('}');
    expect(out).toContain('export {};');
  });
});
