// generated by AppConfigPlugin — не редактировать руками
declare global {
  interface CapsuleTags {
    "input": true;
    "send": true;
    "messages": true;
    "stop": true;
    "clear": true;
    "model": true;
  }

  interface CapsuleAliases {
    "@chat": true;
  }

}
export {};
