/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Controller: typeof import('@capsuletech/web-core').Controller
  const Controllers: typeof import('../registry/wrappers').Controllers
  const Entities: typeof import('../registry/wrappers').Entities
  const Entity: typeof import('@capsuletech/web-core').Entity
  const Feature: typeof import('@capsuletech/web-core').Feature
  const Features: typeof import('../registry/wrappers').Features
  const Page: typeof import('@capsuletech/web-core').Page
  const Shape: typeof import('@capsuletech/web-core').Shape
  const Shapes: typeof import('../registry/wrappers').Shapes
  const Widget: typeof import('@capsuletech/web-core').Widget
  const Widgets: typeof import('../registry/wrappers').Widgets
  const defineEndpoint: typeof import('@capsuletech/web-query').defineEndpoint
  const endpoints: typeof import('../registry/endpoints').endpoints
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Endpoints } from '../registry/endpoints'
  import('../registry/endpoints')
}
