// generated by ExportGeneratorPlugin — не редактировать руками
declare global {
  interface Widgets {
    Chat: {
      Main: typeof import('@widgets/chat/main').default;
    };
    Models: {
      Picker: typeof import('@widgets/models/picker').default;
    };
  }
  interface Entities {
    Chat: {
      Main: typeof import('@entities/chat/main').default;
    };
    Models: {
      Picker: typeof import('@entities/models/picker').default;
    };
  }
  interface Controllers {
    Chat: {
      Main: typeof import('@controllers/chat/main').default;
    };
    Models: {
      Picker: typeof import('@controllers/models/picker').default;
    };
  }
  interface Features {
    Chat: {
      Main: typeof import('@features/chat/main').default;
    };
    Models: {
      Picker: typeof import('@features/models/picker').default;
    };
  }
  interface Shapes {}
}
export {};
