// Auto-generated by @capsuletech/shared-vite router plugin. Do not edit.
import { lazy } from 'solid-js';
import { createFileRoute } from '@tanstack/solid-router';

const Component = lazy(() => import('@pages/_auth/login') as Promise<{ default: any }>);

export const Route = createFileRoute('/_auth/login')({
  component: Component,
});
