// generated by AppConfigPlugin — не редактировать руками
import { registerAliases } from '@capsule/web-state';
import { createApi, setApiClient } from '@capsule/web-query';
import appConfig from '../capsule.app';
import { endpoints } from './registry/endpoints';

registerAliases({
  "@chat": [
    "input",
    "send"
  ]
});

if (appConfig.api) {
  setApiClient(createApi(appConfig.api, endpoints));
}
