// generated by AppConfigPlugin — не редактировать руками
declare global {
  interface CapsuleTags {
    "email": true;
    "password": true;
    "submit": true;
    "nav": true;
    "logout": true;
  }

  interface CapsuleAliases {
    "@login-form": true;
    "@header": true;
  }

}
export {};
