// generated by ExportGeneratorPlugin — не редактировать руками
declare global {
  interface Widgets {
    Demos: {
      Dnd: typeof import('@widgets/demos/dnd').default;
      EditorState: typeof import('@widgets/demos/editorState').default;
      Hub: typeof import('@widgets/demos/hub').default;
      Inspector: typeof import('@widgets/demos/inspector').default;
      Manifests: typeof import('@widgets/demos/manifests').default;
      RendererAuth: typeof import('@widgets/demos/rendererAuth').default;
    };
    Footers: {
      Main: typeof import('@widgets/footers/main').default;
    };
    Forms: {
      Auth: typeof import('@widgets/forms/auth').default;
    };
    Headers: {
      Main: typeof import('@widgets/headers/main').default;
    };
    Lists: {
      Base: typeof import('@widgets/lists/base').default;
    };
  }
  interface Entities {
    Header: {
      Main: typeof import('@entities/header/main').default;
    };
    Viewer: {
      LoginForm: typeof import('@entities/viewer/loginForm').default;
    };
  }
  interface Controllers {
    Universal: {
      Form: typeof import('@controllers/universal/form').default;
      List: typeof import('@controllers/universal/list').default;
      Navigation: typeof import('@controllers/universal/navigation').default;
      Validator: typeof import('@controllers/universal/validator').default;
    };
  }
  interface Features {
    Viewer: {
      Auth: typeof import('@features/viewer/auth').default;
    };
  }
  interface Shapes {
    Header: {
      NavItems: typeof import('@shapes/header/navItems').default;
    };
  }
}
export {};
