// Auto-generated by @capsule/shared-vite router plugin. Do not edit.
import { lazy } from 'solid-js';
import { createFileRoute } from '@tanstack/solid-router';

const Component = lazy(() => import('@pages/welcome') as Promise<{ default: any }>);

export const Route = createFileRoute('/welcome')({
  component: Component,
});
