// Auto-generated by @capsuletech/vite-builder router plugin. Do not edit.
import { lazy } from 'solid-js';
import { createFileRoute } from '@tanstack/solid-router';

const Component = lazy(() => import('@pages/lab/auth/registration') as Promise<{ default: any }>);

export const Route = createFileRoute('/lab/auth/registration')({
  component: Component,
});
