// generated by EndpointsRegistryPlugin — не редактировать руками
import * as user from '../../src/endpoints/user';

export const endpoints = {
  user: user
} as const;
export type Endpoints = typeof endpoints;
