// generated by ExportGeneratorPlugin — не редактировать руками
import { lazy } from 'solid-js';

export const Widgets = {
  Demos: {
    Dnd: lazy(() => import('@widgets/demos/dnd')) as unknown as typeof import('@widgets/demos/dnd').default,
    EditorState: lazy(() => import('@widgets/demos/editorState')) as unknown as typeof import('@widgets/demos/editorState').default,
    Hub: lazy(() => import('@widgets/demos/hub')) as unknown as typeof import('@widgets/demos/hub').default,
    Inspector: lazy(() => import('@widgets/demos/inspector')) as unknown as typeof import('@widgets/demos/inspector').default,
    Manifests: lazy(() => import('@widgets/demos/manifests')) as unknown as typeof import('@widgets/demos/manifests').default,
    RendererAuth: lazy(() => import('@widgets/demos/rendererAuth')) as unknown as typeof import('@widgets/demos/rendererAuth').default
  },
  Footers: {
    Main: lazy(() => import('@widgets/footers/main')) as unknown as typeof import('@widgets/footers/main').default
  },
  Forms: {
    Auth: lazy(() => import('@widgets/forms/_auth')) as unknown as typeof import('@widgets/forms/_auth').default
  },
  Headers: {
    Main: lazy(() => import('@widgets/headers/main')) as unknown as typeof import('@widgets/headers/main').default
  },
  Lists: {
    Base: lazy(() => import('@widgets/lists/base')) as unknown as typeof import('@widgets/lists/base').default
  }
};

export const Entities = {
  Header: {
    Main: lazy(() => import('@entities/header/main')) as unknown as typeof import('@entities/header/main').default
  },
  Viewer: {
    LoginForm: lazy(() => import('@entities/viewer/loginForm')) as unknown as typeof import('@entities/viewer/loginForm').default
  }
};

export const Controllers = {
  Universal: {
    Form: lazy(() => import('@controllers/universal/form')) as unknown as typeof import('@controllers/universal/form').default,
    List: lazy(() => import('@controllers/universal/list')) as unknown as typeof import('@controllers/universal/list').default,
    Navigation: lazy(() => import('@controllers/universal/navigation')) as unknown as typeof import('@controllers/universal/navigation').default,
    Validator: lazy(() => import('@controllers/universal/validator')) as unknown as typeof import('@controllers/universal/validator').default
  }
};

export const Features = {
  Viewer: {
    Auth: lazy(() => import('@features/viewer/_auth')) as unknown as typeof import('@features/viewer/_auth').default
  }
};

export const Shapes = {
  Header: {
    NavItems: lazy(() => import('@shapes/header/navItems')) as unknown as typeof import('@shapes/header/navItems').default
  }
};
