import { existsSync } from 'node:fs';
import { copyFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Plugin } from 'vite';

const __dirname = dirname(fileURLToPath(import.meta.url));

// NOTE: bootstrap.tsx AND index.ts are intentionally NOT in this list.
//  - bootstrap.tsx — generated from LAYER_INIT_ORDER (copy-once would make import
//    ordering fragile).
//  - index.ts (mount entry) — generated by CapsuleRegistryPlugin (ADR 059 Phase 2,
//    generateIndexEntry). Copy-once left existing apps with a stale
//    `createRoot(Bootstrap)` entry, so the embed-aware entry would not apply
//    without a manual `.capsule/` wipe (canon §0/§1: no manual-workaround).
// Both are always-regenerated codegen, owned by CapsuleRegistryPlugin.
const FILES = ['index.html', 'paths.config.json', 'styles.css'] as const;

/**
 * Гарантирует наличие статических entry-файлов (`index.html`,
 * `paths.config.json`, `styles.css`) в `.capsule/`. Если их нет — копирует
 * из встроенных шаблонов. Нужно для клонированных/свежесозданных приложений,
 * где CLI init ещё не запускался.
 *
 * `bootstrap.tsx` и `index.ts` НЕ входят в этот список — они полностью
 * генерируются `CapsuleRegistryPlugin` (по `LAYER_INIT_ORDER` и
 * `generateIndexEntry` соответственно) и всегда актуальны (ADR 059 Phase 2).
 *
 * Файлы пишутся реально на диск (а не отдаются через middleware), чтобы их
 * мог увидеть TanStackRouterVite и любой другой плагин, работающий с FS.
 */
export const EnsureScaffoldPlugin = (capsuleRoot: string): Plugin => ({
  name: 'capsule-ensure-scaffold',
  enforce: 'pre',
  async config() {
    const absRoot = resolve(capsuleRoot);
    await mkdir(absRoot, { recursive: true });
    for (const name of FILES) {
      const dest = resolve(absRoot, name);
      if (existsSync(dest)) continue;
      const src = resolve(__dirname, 'template', `${name}.template`);
      await copyFile(src, dest);
      console.log(`📄 Создан ${name} в ${absRoot}`);
    }
  },
});
