export { connectionCollector } from './connection';
export { domStatsCollector } from './domStats';
export type { IDomStatsOpts } from './domStats';
export { errorsCollector } from './errors';
export { eventTimingCollector } from './eventTiming';
export type { IEventTimingOpts } from './eventTiming';
export { fpsCollector } from './fps';
export type { IFpsOpts } from './fps';
export { loafCollector } from './loaf';
export type { ILoafOpts } from './loaf';
export { longTasksCollector } from './longTasks';
export type { ILongTasksOpts } from './longTasks';
export { memoryCollector } from './memory';
export type { IMemoryOpts } from './memory';
export { navigationCollector } from './navigation';
export { networkCollector } from './network';
export type { INetworkOpts } from './network';
export { networkDeepCollector } from './networkDeep';
export type { INetworkDeepOpts } from './networkDeep';
export { userTimingCollector } from './userTiming';
export { webVitalsCollector } from './webVitals';
export type { IWebVitalsOpts } from './webVitals';
