// Auto-generated by @capsuletech/vite-builder router plugin. Do not edit.
import { lazy } from 'solid-js';
import { createFileRoute } from '@tanstack/solid-router';

const Component = lazy(() => import('@pages/index') as Promise<{ default: any }>);

export const Route = createFileRoute('/')({
  component: Component,
});
