/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as LabRouteRouteImport } from './lab/route'
import { Route as ChatRouteRouteImport } from './chat/route'
import { Route as IndexRouteImport } from './index'
import { Route as LabAuthRouteRouteImport } from './lab/auth/route'
import { Route as LabAuthRegistrationRouteImport } from './lab/auth/registration'
import { Route as LabAuthLoginRouteImport } from './lab/auth/login'
import { Route as LabHomeCardRouteRouteImport } from './lab/home/card/route'
import { Route as LabHomeCardIdRouteImport } from './lab/home/card/$id'
import { Route as LabHomePlaygroundBRouteImport } from './lab/home/_playground/b'
import { Route as LabHomePlaygroundARouteImport } from './lab/home/_playground/a'

const LabRouteRoute = LabRouteRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAuthRouteRoute = LabAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabAuthRegistrationRoute = LabAuthRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => LabAuthRouteRoute,
} as any)
const LabAuthLoginRoute = LabAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LabAuthRouteRoute,
} as any)
const LabHomeCardRouteRoute = LabHomeCardRouteRouteImport.update({
  id: '/home/card',
  path: '/home/card',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabHomeCardIdRoute = LabHomeCardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LabHomeCardRouteRoute,
} as any)
const LabHomePlaygroundBRoute = LabHomePlaygroundBRouteImport.update({
  id: '/home/_playground/b',
  path: '/home/b',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabHomePlaygroundARoute = LabHomePlaygroundARouteImport.update({
  id: '/home/_playground/a',
  path: '/home/a',
  getParentRoute: () => LabRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRoute
  '/lab': typeof LabRouteRouteWithChildren
  '/lab/auth': typeof LabAuthRouteRouteWithChildren
  '/lab/home/card': typeof LabHomeCardRouteRouteWithChildren
  '/lab/auth/login': typeof LabAuthLoginRoute
  '/lab/auth/registration': typeof LabAuthRegistrationRoute
  '/lab/home/a': typeof LabHomePlaygroundARoute
  '/lab/home/b': typeof LabHomePlaygroundBRoute
  '/lab/home/card/$id': typeof LabHomeCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRoute
  '/lab': typeof LabRouteRouteWithChildren
  '/lab/auth': typeof LabAuthRouteRouteWithChildren
  '/lab/home/card': typeof LabHomeCardRouteRouteWithChildren
  '/lab/auth/login': typeof LabAuthLoginRoute
  '/lab/auth/registration': typeof LabAuthRegistrationRoute
  '/lab/home/a': typeof LabHomePlaygroundARoute
  '/lab/home/b': typeof LabHomePlaygroundBRoute
  '/lab/home/card/$id': typeof LabHomeCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRoute
  '/lab': typeof LabRouteRouteWithChildren
  '/lab/auth': typeof LabAuthRouteRouteWithChildren
  '/lab/home/card': typeof LabHomeCardRouteRouteWithChildren
  '/lab/auth/login': typeof LabAuthLoginRoute
  '/lab/auth/registration': typeof LabAuthRegistrationRoute
  '/lab/home/_playground/a': typeof LabHomePlaygroundARoute
  '/lab/home/_playground/b': typeof LabHomePlaygroundBRoute
  '/lab/home/card/$id': typeof LabHomeCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/lab'
    | '/lab/auth'
    | '/lab/home/card'
    | '/lab/auth/login'
    | '/lab/auth/registration'
    | '/lab/home/a'
    | '/lab/home/b'
    | '/lab/home/card/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/lab'
    | '/lab/auth'
    | '/lab/home/card'
    | '/lab/auth/login'
    | '/lab/auth/registration'
    | '/lab/home/a'
    | '/lab/home/b'
    | '/lab/home/card/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/lab'
    | '/lab/auth'
    | '/lab/home/card'
    | '/lab/auth/login'
    | '/lab/auth/registration'
    | '/lab/home/_playground/a'
    | '/lab/home/_playground/b'
    | '/lab/home/card/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRouteRoute: typeof ChatRouteRoute
  LabRouteRoute: typeof LabRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/auth': {
      id: '/lab/auth'
      path: '/auth'
      fullPath: '/lab/auth'
      preLoaderRoute: typeof LabAuthRouteRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/auth/registration': {
      id: '/lab/auth/registration'
      path: '/registration'
      fullPath: '/lab/auth/registration'
      preLoaderRoute: typeof LabAuthRegistrationRouteImport
      parentRoute: typeof LabAuthRouteRoute
    }
    '/lab/auth/login': {
      id: '/lab/auth/login'
      path: '/login'
      fullPath: '/lab/auth/login'
      preLoaderRoute: typeof LabAuthLoginRouteImport
      parentRoute: typeof LabAuthRouteRoute
    }
    '/lab/home/card': {
      id: '/lab/home/card'
      path: '/home/card'
      fullPath: '/lab/home/card'
      preLoaderRoute: typeof LabHomeCardRouteRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/home/card/$id': {
      id: '/lab/home/card/$id'
      path: '/$id'
      fullPath: '/lab/home/card/$id'
      preLoaderRoute: typeof LabHomeCardIdRouteImport
      parentRoute: typeof LabHomeCardRouteRoute
    }
    '/lab/home/_playground/b': {
      id: '/lab/home/_playground/b'
      path: '/home/b'
      fullPath: '/lab/home/b'
      preLoaderRoute: typeof LabHomePlaygroundBRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/home/_playground/a': {
      id: '/lab/home/_playground/a'
      path: '/home/a'
      fullPath: '/lab/home/a'
      preLoaderRoute: typeof LabHomePlaygroundARouteImport
      parentRoute: typeof LabRouteRoute
    }
  }
}

interface LabAuthRouteRouteChildren {
  LabAuthLoginRoute: typeof LabAuthLoginRoute
  LabAuthRegistrationRoute: typeof LabAuthRegistrationRoute
}

const LabAuthRouteRouteChildren: LabAuthRouteRouteChildren = {
  LabAuthLoginRoute: LabAuthLoginRoute,
  LabAuthRegistrationRoute: LabAuthRegistrationRoute,
}

const LabAuthRouteRouteWithChildren = LabAuthRouteRoute._addFileChildren(
  LabAuthRouteRouteChildren,
)

interface LabHomeCardRouteRouteChildren {
  LabHomeCardIdRoute: typeof LabHomeCardIdRoute
}

const LabHomeCardRouteRouteChildren: LabHomeCardRouteRouteChildren = {
  LabHomeCardIdRoute: LabHomeCardIdRoute,
}

const LabHomeCardRouteRouteWithChildren =
  LabHomeCardRouteRoute._addFileChildren(LabHomeCardRouteRouteChildren)

interface LabRouteRouteChildren {
  LabAuthRouteRoute: typeof LabAuthRouteRouteWithChildren
  LabHomeCardRouteRoute: typeof LabHomeCardRouteRouteWithChildren
  LabHomePlaygroundARoute: typeof LabHomePlaygroundARoute
  LabHomePlaygroundBRoute: typeof LabHomePlaygroundBRoute
}

const LabRouteRouteChildren: LabRouteRouteChildren = {
  LabAuthRouteRoute: LabAuthRouteRouteWithChildren,
  LabHomeCardRouteRoute: LabHomeCardRouteRouteWithChildren,
  LabHomePlaygroundARoute: LabHomePlaygroundARoute,
  LabHomePlaygroundBRoute: LabHomePlaygroundBRoute,
}

const LabRouteRouteWithChildren = LabRouteRoute._addFileChildren(
  LabRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRouteRoute: ChatRouteRoute,
  LabRouteRoute: LabRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
