// Auto-generated by @capsuletech/shared-vite router plugin. Do not edit.
import { lazy } from 'solid-js';
import { createFileRoute } from '@tanstack/solid-router';

const Component = lazy(() => import('@pages/lab/home/card/index') as Promise<{ default: any }>);

export const Route = createFileRoute('/lab/home/card')({
  component: Component,
});
