// generated by EndpointsRegistryPlugin — не редактировать руками
import type { InferApi } from '@capsuletech/web-query';
import type { Endpoints } from '../registry/endpoints';

declare global {
  /**
   * Typed-proxy, который вернёт `createApi(...)` и инжектится в Feature
   * как `services.api`. Структура — InferApi от auto-discovered endpoints-реестра.
   */
  interface CapsuleApi extends InferApi<Endpoints> {}
}
export {};
