// generated by ExportGeneratorPlugin — не редактировать руками
declare global {
  interface Widgets {
    Welcome: typeof import('@widgets/welcome').default;
  }
  interface Entities {
    Hello: typeof import('@entities/hello').default;
  }
  interface Controllers {}
  interface Features {}
  interface Shapes {}
}
export {};
